# Generated by Django 4.2.4 on 2026-03-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vital', 'Vital'), ('lab', 'Lab'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('loinc_code', models.CharField(blank=True, max_length=30)),
                ('value_string', models.CharField(blank=True, max_length=255)),
                ('value_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('effective_datetime', models.DateTimeField(blank=True, null=True)),
                ('interpretation', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rxnorm_code', models.CharField(blank=True, max_length=30)),
                ('dosage_text', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescriber', models.CharField(blank=True, max_length=255)),
                ('indication', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('cvx_code', models.CharField(blank=True, max_length=20)),
                ('occurrence_date', models.DateField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('performer', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('snomed_code', models.CharField(blank=True, max_length=30)),
                ('clinical_status', models.CharField(blank=True, max_length=30)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('abatement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=255)),
                ('rxnorm_code', models.CharField(blank=True, max_length=30)),
                ('snomed_code', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('criticality', models.CharField(blank=True, max_length=20)),
                ('reaction', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patientprofile')),
            ],
        ),
    ]
