# Generated by Django 4.2.4 on 2026-06-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0002_alter_allergy_options_alter_encounter_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("participants", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_teams",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Care Team",
                "verbose_name_plural": "Care Team",
            },
        ),
    ]
