# Generated by Django 4.2.4 on 2026-06-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        ("clinical", "0006_careplan_procedure_specimen_procedureperformer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("device_type", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("lot_number", models.CharField(blank=True, max_length=255)),
                ("distinct_identifier", models.CharField(blank=True, max_length=255)),
                ("udi_carrier", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="clinical.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PractitionerRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("role", models.CharField(blank=True, max_length=255)),
                ("specialty", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practitioner_roles",
                        to="clinical.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practitioner_roles",
                        to="clinical.organization",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="clinical.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Role",
                "verbose_name_plural": "Practitioner Roles",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("intent", models.CharField(blank=True, max_length=30)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("priority", models.CharField(blank=True, max_length=30)),
                ("do_not_perform", models.BooleanField(default=False)),
                ("authored_on", models.DateTimeField(blank=True, null=True)),
                ("occurrence_start", models.DateTimeField(blank=True, null=True)),
                ("occurrence_end", models.DateTimeField(blank=True, null=True)),
                ("performer_type", models.CharField(blank=True, max_length=255)),
                ("location_code", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("patient_instruction", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "care_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_requests",
                        to="clinical.careplan",
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_requests",
                        to="clinical.condition",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_requests",
                        to="clinical.location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "performers_care_teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_requests",
                        to="clinical.careteam",
                    ),
                ),
                (
                    "performers_devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_request_performances",
                        to="clinical.device",
                    ),
                ),
                (
                    "performers_organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_request_performances",
                        to="clinical.organization",
                    ),
                ),
                (
                    "performers_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_request_performances",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "performers_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_request_performances",
                        to="clinical.practitionerrole",
                    ),
                ),
                (
                    "replaces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="replacement_requests",
                        to="clinical.servicerequest",
                    ),
                ),
                (
                    "requester_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_services",
                        to="clinical.device",
                    ),
                ),
                (
                    "requester_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_services",
                        to="clinical.organization",
                    ),
                ),
                (
                    "requester_practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_services",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "requester_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_services",
                        to="clinical.practitionerrole",
                    ),
                ),
                (
                    "specimens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_requests",
                        to="clinical.specimen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
            },
        ),
        migrations.CreateModel(
            name="EpisodeOfCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=30)),
                ("episode_type", models.CharField(blank=True, max_length=255)),
                ("diagnosis_summary", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "care_manager_practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_episodes",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "care_manager_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_episodes",
                        to="clinical.practitionerrole",
                    ),
                ),
                (
                    "care_teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="episodes_of_care",
                        to="clinical.careteam",
                    ),
                ),
                (
                    "managing_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episodes_of_care",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes_of_care",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "referral_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="episodes_of_care",
                        to="clinical.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode of Care",
                "verbose_name_plural": "Episodes of Care",
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="episodes_of_care",
            field=models.ManyToManyField(
                blank=True, related_name="encounters", to="clinical.episodeofcare"
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observations",
                to="clinical.device",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="service_requests",
            field=models.ManyToManyField(
                blank=True, related_name="procedures", to="clinical.servicerequest"
            ),
        ),
    ]
