# Generated by Django 4.2.4 on 2026-06-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        (
            "documents",
            "0002_clinicaldocument_authors_clinicaldocument_custodian_and_more",
        ),
        (
            "clinical",
            "0007_device_practitionerrole_servicerequest_episodeofcare_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                ("effective_datetime", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("protocol", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("prognosis", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor_practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_impressions",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "assessor_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_impressions",
                        to="clinical.practitionerrole",
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clinical_impressions",
                        to="clinical.condition",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_impressions",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "investigations_observations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clinical_impression_investigations",
                        to="clinical.observation",
                    ),
                ),
                (
                    "observations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clinical_impressions",
                        to="clinical.observation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_impressions",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "problems",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clinical_impression_problem_refs",
                        to="clinical.condition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Impression",
                "verbose_name_plural": "Clinical Impressions",
            },
        ),
        migrations.CreateModel(
            name="FamilyMemberHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=30)),
                ("relationship", models.CharField(max_length=255)),
                ("sex", models.CharField(blank=True, max_length=30)),
                ("born_date", models.DateField(blank=True, null=True)),
                ("born_text", models.CharField(blank=True, max_length=255)),
                ("age_text", models.CharField(blank=True, max_length=255)),
                ("estimated_age", models.BooleanField(default=False)),
                ("deceased", models.BooleanField(blank=True, null=True)),
                ("deceased_date", models.DateField(blank=True, null=True)),
                ("deceased_text", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="family_member_histories",
                        to="clinical.condition",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_member_histories",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Member History",
                "verbose_name_plural": "Family Member Histories",
            },
        ),
        migrations.CreateModel(
            name="FamilyMemberHistoryCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_text", models.CharField(max_length=255)),
                ("outcome", models.CharField(blank=True, max_length=255)),
                ("contributed_to_death", models.BooleanField(blank=True, null=True)),
                ("onset_text", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_history_condition_links",
                        to="clinical.condition",
                    ),
                ),
                (
                    "family_member_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_links",
                        to="clinical.familymemberhistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalImpressionFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finding_text", models.CharField(blank=True, max_length=255)),
                ("basis", models.TextField(blank=True)),
                (
                    "clinical_impression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finding_links",
                        to="clinical.clinicalimpression",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_impression_findings",
                        to="clinical.condition",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_impression_findings",
                        to="clinical.observation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdverseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actuality", models.CharField(blank=True, max_length=30)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("event", models.CharField(blank=True, max_length=255)),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                ("detected_date", models.DateTimeField(blank=True, null=True)),
                ("recorded_date", models.DateTimeField(blank=True, null=True)),
                ("seriousness", models.CharField(blank=True, max_length=255)),
                ("severity", models.CharField(blank=True, max_length=255)),
                ("outcome", models.CharField(blank=True, max_length=255)),
                ("suspect_entity_summary", models.TextField(blank=True)),
                ("causality_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor_devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_contributions",
                        to="clinical.device",
                    ),
                ),
                (
                    "contributor_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_contributions",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "contributor_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_contributions",
                        to="clinical.practitionerrole",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adverse_events",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adverse_events",
                        to="clinical.location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverse_events",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "recorder_practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_adverse_events",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "recorder_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_adverse_events",
                        to="clinical.practitionerrole",
                    ),
                ),
                (
                    "reference_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_events",
                        to="documents.clinicaldocument",
                    ),
                ),
                (
                    "resulting_conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_events",
                        to="clinical.condition",
                    ),
                ),
                (
                    "subject_medical_history_conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_medical_history_refs",
                        to="clinical.condition",
                    ),
                ),
                (
                    "subject_medical_history_immunizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_medical_history_refs",
                        to="clinical.immunization",
                    ),
                ),
                (
                    "subject_medical_history_observations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_medical_history_refs",
                        to="clinical.observation",
                    ),
                ),
                (
                    "subject_medical_history_procedures",
                    models.ManyToManyField(
                        blank=True,
                        related_name="adverse_event_medical_history_refs",
                        to="clinical.procedure",
                    ),
                ),
                (
                    "suspect_devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suspected_adverse_events",
                        to="clinical.device",
                    ),
                ),
                (
                    "suspect_immunizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suspected_adverse_events",
                        to="clinical.immunization",
                    ),
                ),
                (
                    "suspect_medications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suspected_adverse_events",
                        to="clinical.medication",
                    ),
                ),
                (
                    "suspect_procedures",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suspected_adverse_events",
                        to="clinical.procedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adverse Event",
                "verbose_name_plural": "Adverse Events",
            },
        ),
    ]
