# Generated by Django 4.2.4 on 2026-06-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_options'),
        ('clinical', '0011_relatedperson_careteamparticipant_related_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='FHIR active: whether this group record is in active use.')),
                ('group_type', models.CharField(blank=True, help_text='FHIR type: person, practitioner, device, etc.', max_length=30)),
                ('actual', models.BooleanField(default=True, help_text='FHIR actual: actual members vs intended/definitional group.')),
                ('code', models.CharField(blank=True, help_text='FHIR code: kind of group members.', max_length=255)),
                ('name', models.CharField(blank=True, help_text='FHIR name: human label for the group.', max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='FHIR quantity: number of members.', null=True)),
                ('characteristic_summary', models.TextField(blank=True, help_text='FHIR characteristic: included/excluded member traits.')),
                ('notes', models.TextField(blank=True, help_text='Imported notes or source text for this group.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managing_organization', models.ForeignKey(blank=True, help_text='FHIR managingEntity: organization responsible for the group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='clinical.organization')),
                ('managing_practitioner', models.ForeignKey(blank=True, help_text='FHIR managingEntity: practitioner responsible for the group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='clinical.practitioner')),
                ('managing_related_person', models.ForeignKey(blank=True, help_text='FHIR managingEntity: related person responsible for the group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='clinical.relatedperson')),
                ('managing_role', models.ForeignKey(blank=True, help_text='FHIR managingEntity: practitioner role responsible for the group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='clinical.practitionerrole')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='FHIR active: whether this person record is in active use.')),
                ('name', models.CharField(blank=True, help_text='FHIR name: name associated with the person.', max_length=255)),
                ('gender', models.CharField(blank=True, help_text='FHIR gender: administrative gender.', max_length=30)),
                ('birth_date', models.DateField(blank=True, help_text='FHIR birthDate: date the person was born.', null=True)),
                ('phone', models.CharField(blank=True, help_text='FHIR telecom: phone contact.', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='FHIR telecom: email contact.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='FHIR address: one or more addresses for the person.')),
                ('notes', models.TextField(blank=True, help_text='Imported notes or source text for this person.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managing_organization', models.ForeignKey(blank=True, help_text='FHIR managingOrganization: custodian of the person record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_people', to='clinical.organization')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_display', models.CharField(blank=True, max_length=255)),
                ('target_reference', models.CharField(blank=True, max_length=255)),
                ('assurance', models.CharField(blank=True, help_text='FHIR assurance: level1, level2, level3, or level4.', max_length=30)),
                ('linked_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_person_records', to='clinical.person')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identity_links', to='patients.patientprofile')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_records', to='clinical.person')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identity_links', to='clinical.practitioner')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identity_links', to='clinical.relatedperson')),
            ],
            options={
                'verbose_name': 'Person Link',
                'verbose_name_plural': 'Person Links',
            },
        ),
        migrations.CreateModel(
            name='FHIRGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_display', models.CharField(blank=True, max_length=255)),
                ('entity_reference', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.device')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='clinical.fhirgroup')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.medication')),
                ('member_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_group_memberships', to='clinical.fhirgroup')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='patients.patientprofile')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.practitioner')),
                ('practitioner_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.practitionerrole')),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
            },
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Optional shared Person identity for this patient-specific related person role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_person_roles', to='clinical.person'),
        ),
    ]
