# Generated by Django 4.2.4 on 2026-06-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_options'),
        ('clinical', '0013_devicerequest_riskassessment_goal_deviceusestatement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='category',
            field=models.CharField(blank=True, help_text='FHIR category: food, medication, environment, or biologic.', max_length=50),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='criticality',
            field=models.CharField(blank=True, help_text='FHIR criticality: estimate of potential clinical harm.', max_length=20),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional allergy/intolerance comments.'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(help_text='FHIR patient: person who has the allergy or intolerance.', on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='reaction',
            field=models.CharField(blank=True, help_text='FHIR reaction.manifestation: observed or reported reaction.', max_length=255),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='rxnorm_code',
            field=models.CharField(blank=True, help_text='FHIR code.coding: RxNorm code for medication allergies.', max_length=30),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(blank=True, help_text='FHIR reaction.severity: mild, moderate, or severe.', max_length=20),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='snomed_code',
            field=models.CharField(blank=True, help_text='FHIR code.coding: SNOMED CT code when present.', max_length=30),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='substance',
            field=models.CharField(help_text='FHIR code: substance, product, or class that causes the reaction.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='active',
            field=models.BooleanField(default=True, help_text='FHIR active: whether this body structure record is in active use.'),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='description',
            field=models.TextField(blank=True, help_text='FHIR description: text description of the body structure.'),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='image_summary',
            field=models.TextField(blank=True, help_text='FHIR image: summary of attached body-site images.'),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='location',
            field=models.CharField(blank=True, help_text='FHIR location: body site or anatomical location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='location_qualifier',
            field=models.CharField(blank=True, help_text='FHIR locationQualifier: laterality or relative location details.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='morphology',
            field=models.CharField(blank=True, help_text='FHIR morphology: kind of structure or abnormality, such as tumor, wound, or surgical site.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional imported body structure notes.'),
        ),
        migrations.AlterField(
            model_name='bodystructure',
            name='patient',
            field=models.ForeignKey(help_text='FHIR patient: patient this anatomical structure belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='body_structures', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='author_display',
            field=models.CharField(blank=True, help_text='FHIR author: person or organization responsible for the plan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='care_teams',
            field=models.ManyToManyField(blank=True, help_text='FHIR careTeam: teams involved in carrying out the plan.', related_name='care_plans', to='clinical.careteam'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='category',
            field=models.CharField(blank=True, help_text='FHIR category: type or grouping of care plan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR addresses: conditions or concerns addressed by the plan.', related_name='care_plans', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='description',
            field=models.TextField(blank=True, help_text="FHIR description: summary of the plan's scope and purpose."),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR period.end: when the plan ends.', null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='intent',
            field=models.CharField(blank=True, help_text='FHIR intent: proposal, plan, order, option, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional care plan comments.'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient the care plan is for.', on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR period.start: when the plan starts.', null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: draft, active, on-hold, revoked, completed, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='title',
            field=models.CharField(help_text='FHIR title: human-friendly name for the care plan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='category',
            field=models.CharField(blank=True, help_text='FHIR category: type of team, such as condition-specific or long-term care.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR period.end: when team responsibility ended.', null=True),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='managing_organizations',
            field=models.ManyToManyField(blank=True, help_text='FHIR managingOrganization: organization responsible for the care team.', related_name='managed_care_teams', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='name',
            field=models.CharField(help_text='FHIR name: human-readable care team name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional care team comments.'),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='participants',
            field=models.TextField(blank=True, help_text='FHIR participant: imported participant summary when structured links are not available.'),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient whose care team this is.', on_delete=django.db.models.deletion.CASCADE, related_name='care_teams', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='reason',
            field=models.CharField(blank=True, help_text='FHIR reasonCode/reasonReference: why the care team exists.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR period.start: when team responsibility started.', null=True),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: proposed, active, suspended, inactive, or entered-in-error.', max_length=30),
        ),
        migrations.AlterField(
            model_name='condition',
            name='abatement_date',
            field=models.DateField(blank=True, help_text='FHIR abatement[x]: estimated or known resolution/end date.', null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='clinical_status',
            field=models.CharField(blank=True, help_text='FHIR clinicalStatus: active, recurrence, relapse, inactive, remission, or resolved.', max_length=30),
        ),
        migrations.AlterField(
            model_name='condition',
            name='icd10_code',
            field=models.CharField(blank=True, help_text='FHIR code.coding: ICD-10 diagnosis code when present.', max_length=20),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(help_text='FHIR code: problem, diagnosis, or condition name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='condition',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: comments or clinical context for the condition.'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='onset_date',
            field=models.DateField(blank=True, help_text='FHIR onset[x]: estimated or known start date.', null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient who has, had, or may have this condition.', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='snomed_code',
            field=models.CharField(blank=True, help_text='FHIR code.coding: SNOMED CT concept code when present.', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, help_text='FHIR type: kind or category of device.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='display_name',
            field=models.CharField(help_text='FHIR deviceName/type: human-readable device name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='distinct_identifier',
            field=models.CharField(blank=True, help_text='FHIR distinctIdentifier: distinct fixed device identifier.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, help_text='FHIR location: where the device is found or used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='clinical.location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lot_number',
            field=models.CharField(blank=True, help_text='FHIR lotNumber: manufacturing lot number.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='FHIR manufacturer: device manufacturer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.CharField(blank=True, help_text="FHIR modelNumber: manufacturer's model number.", max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional device comments.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='FHIR owner: organization responsible for the device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='FHIR patient: patient associated with the device when applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='FHIR serialNumber: device serial number.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: active, inactive, entered-in-error, or unknown.', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='udi_carrier',
            field=models.TextField(blank=True, help_text='FHIR udiCarrier: unique device identifier carrier details.'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='authored_on',
            field=models.DateTimeField(blank=True, help_text='FHIR authoredOn: when the request was created.', null=True),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='care_plans',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn: care plans this request fulfills or follows.', related_name='device_requests', to='clinical.careplan'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='code',
            field=models.CharField(help_text='FHIR code[x]: requested device, device type, or coded device request.', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: conditions supporting the request.', related_name='device_requests', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='FHIR codeReference: specific device being requested.', related_name='device_requests', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='diagnostic_reports',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: diagnostic reports supporting the request.', related_name='device_requests', to='clinical.diagnosticreport'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='FHIR encounter: visit or encounter where the device was requested.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requests', to='clinical.encounter'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='intent',
            field=models.CharField(blank=True, help_text='FHIR intent: proposal, plan, directive, order, original-order, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional request comments.'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='observations',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: observations supporting the request.', related_name='device_requests', to='clinical.observation'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='occurrence_end',
            field=models.DateTimeField(blank=True, help_text='FHIR occurrencePeriod.end: requested end time when a period is used.', null=True),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='occurrence_start',
            field=models.DateTimeField(blank=True, help_text='FHIR occurrence[x]: requested start or occurrence time.', null=True),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient who needs or is prescribed the device.', on_delete=django.db.models.deletion.CASCADE, related_name='device_requests', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='performers_organizations',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: organizations asked to fulfill the request.', related_name='device_request_performances', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='performers_practitioners',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: practitioners asked to fulfill the request.', related_name='device_request_performances', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='performers_roles',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: practitioner roles asked to fulfill the request.', related_name='device_request_performances', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='priority',
            field=models.CharField(blank=True, help_text='FHIR priority: routine, urgent, asap, or stat.', max_length=30),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='reason',
            field=models.CharField(blank=True, help_text='FHIR reasonCode: coded reason for the device request.', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='replaces',
            field=models.ManyToManyField(blank=True, help_text='FHIR replaces: prior device requests replaced by this request.', related_name='replacement_device_requests', to='clinical.devicerequest'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='requester_practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR requester: practitioner who initiated the device request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_devices', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='requester_role',
            field=models.ForeignKey(blank=True, help_text='FHIR requester: practitioner role that initiated the device request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_devices', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='risk_assessments',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: risk assessments supporting the request.', related_name='device_requests', to='clinical.riskassessment'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='service_requests',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn: service requests this device request is based on.', related_name='device_requests', to='clinical.servicerequest'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: draft, active, on-hold, revoked, completed, entered-in-error, or unknown.', max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='based_on_device_requests',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn: device requests this use statement fulfills or follows.', related_name='device_use_statements', to='clinical.devicerequest'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='based_on_service_requests',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn: service requests this use statement fulfills or follows.', related_name='device_use_statements', to='clinical.servicerequest'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='body_site',
            field=models.CharField(blank=True, help_text='FHIR bodySite: anatomical location where the device is used.', max_length=255),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='device',
            field=models.ForeignKey(blank=True, help_text='FHIR device: device being used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_statements', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional device use comments.'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient who uses or used the device.', on_delete=django.db.models.deletion.CASCADE, related_name='device_use_statements', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='reason_conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: conditions supporting device use.', related_name='device_use_statements', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='reason_diagnostic_reports',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: diagnostic reports supporting device use.', related_name='device_use_statements', to='clinical.diagnosticreport'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='reason_observations',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: observations supporting device use.', related_name='device_use_statements', to='clinical.observation'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='reason_risk_assessments',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: risk assessments supporting device use.', related_name='device_use_statements', to='clinical.riskassessment'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='recorded_on',
            field=models.DateTimeField(blank=True, help_text='FHIR recordedOn: when the statement was recorded.', null=True),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='source_practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR source: practitioner who provided the statement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_use_statements', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='source_related_person',
            field=models.ForeignKey(blank=True, help_text='FHIR source: related person who provided the statement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_use_statements', to='clinical.relatedperson'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='source_role',
            field=models.ForeignKey(blank=True, help_text='FHIR source: practitioner role that provided the statement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_use_statements', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: active, completed, entered-in-error, intended, stopped, or on-hold.', max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='timing_end',
            field=models.DateTimeField(blank=True, help_text='FHIR timingPeriod.end: when device use ended.', null=True),
        ),
        migrations.AlterField(
            model_name='deviceusestatement',
            name='timing_start',
            field=models.DateTimeField(blank=True, help_text='FHIR timing[x]: when device use started or occurred.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(blank=True, help_text='FHIR class/type: setting or kind of encounter, such as office, ED, inpatient.', max_length=100),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='FHIR period.end: encounter end time.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='episodes_of_care',
            field=models.ManyToManyField(blank=True, help_text='FHIR episodeOfCare: broader care episodes this encounter belongs to.', related_name='encounters', to='clinical.episodeofcare'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='facility_name',
            field=models.CharField(blank=True, help_text='FHIR location.location: facility or location display.', max_length=255),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient present or involved in the encounter.', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider_name',
            field=models.CharField(blank=True, help_text='FHIR participant.individual: provider or participant display.', max_length=255),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.CharField(blank=True, help_text='FHIR reasonCode/reasonReference: reason for the encounter.', max_length=255),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='FHIR period.start: encounter start time.', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: planned, arrived, in-progress, finished, cancelled, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='summary',
            field=models.TextField(blank=True, help_text='FHIR text/note: encounter summary or imported narrative.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='achievement_status',
            field=models.CharField(blank=True, help_text='FHIR achievementStatus: in-progress, improving, worsening, achieved, not-achieved, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='addresses_conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR addresses: conditions this goal addresses.', related_name='goals', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='addresses_medications',
            field=models.ManyToManyField(blank=True, help_text='FHIR addresses: medications this goal addresses.', related_name='goals', to='clinical.medication'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='addresses_observations',
            field=models.ManyToManyField(blank=True, help_text='FHIR addresses: observations this goal addresses.', related_name='goals', to='clinical.observation'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='addresses_risk_assessments',
            field=models.ManyToManyField(blank=True, help_text='FHIR addresses: risk assessments this goal addresses.', related_name='goals', to='clinical.riskassessment'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='addresses_service_requests',
            field=models.ManyToManyField(blank=True, help_text='FHIR addresses: service requests this goal addresses.', related_name='goals', to='clinical.servicerequest'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, help_text='FHIR category: dietary, safety, behavioral, nursing, physiotherapy, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(help_text='FHIR description: desired objective or outcome.', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='expressed_by_practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR expressedBy: practitioner who expressed or proposed the goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressed_goals', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='expressed_by_related_person',
            field=models.ForeignKey(blank=True, help_text='FHIR expressedBy: related person who expressed or proposed the goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressed_goals', to='clinical.relatedperson'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='expressed_by_role',
            field=models.ForeignKey(blank=True, help_text='FHIR expressedBy: practitioner role that expressed or proposed the goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressed_goals', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='lifecycle_status',
            field=models.CharField(blank=True, help_text='FHIR lifecycleStatus: proposed, planned, accepted, active, on-hold, completed, cancelled, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional goal comments.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='outcome_observations',
            field=models.ManyToManyField(blank=True, help_text='FHIR outcomeReference: observations documenting goal outcome.', related_name='goal_outcomes', to='clinical.observation'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='outcome_summary',
            field=models.TextField(blank=True, help_text='FHIR outcomeCode: coded outcome achieved or observed.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient this goal is for.', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.CharField(blank=True, help_text='FHIR priority: mutually agreed importance of achieving the goal.', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR start[x]: when pursuit of the goal begins.', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status_date',
            field=models.DateField(blank=True, help_text='FHIR statusDate: when the current status was established.', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status_reason',
            field=models.TextField(blank=True, help_text='FHIR statusReason: reason for current lifecycle status.'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='subject_group',
            field=models.ForeignKey(blank=True, help_text='FHIR subject: group this goal is for, when not patient-specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='clinical.fhirgroup'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_summary',
            field=models.TextField(blank=True, help_text='FHIR target: target measure, detail, and due date/duration.'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='cvx_code',
            field=models.CharField(blank=True, help_text='FHIR vaccineCode.coding: CVX vaccine code when present.', max_length=20),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='lot_number',
            field=models.CharField(blank=True, help_text='FHIR lotNumber: vaccine lot identifier.', max_length=100),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='FHIR manufacturer: vaccine manufacturer display.', max_length=255),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional immunization comments.'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='FHIR occurrence[x]: when the vaccine was administered.', null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='patient',
            field=models.ForeignKey(help_text='FHIR patient: person who received the vaccine.', on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='performer',
            field=models.CharField(blank=True, help_text='FHIR performer.actor: person or organization that administered or recorded the immunization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='vaccine_name',
            field=models.CharField(help_text='FHIR vaccineCode: vaccine product administered.', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_text',
            field=models.CharField(blank=True, help_text='FHIR dosage.text: patient-facing or prescriber dosage instructions.', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR effectivePeriod.end: end date when known.', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, help_text='FHIR dosage.timing: when or how often the medication is taken.', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='indication',
            field=models.CharField(blank=True, help_text='FHIR reasonCode/reasonReference: reason or condition being treated.', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='FHIR medication[x]: medication name or coded concept.', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional medication comments.'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject/patient: person taking or prescribed the medication.', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prescriber',
            field=models.CharField(blank=True, help_text='FHIR requester/informationSource: prescriber or reporting source display.', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='route',
            field=models.CharField(blank=True, help_text='FHIR dosage.route: how the medication is taken or given.', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='rxnorm_code',
            field=models.CharField(blank=True, help_text='FHIR medicationCodeableConcept.coding: RxNorm code when present.', max_length=30),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR effectivePeriod.start/authoredOn: start or authored date when known.', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: active, completed, stopped, intended, entered-in-error, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='category',
            field=models.CharField(choices=[('vital', 'Vital'), ('lab', 'Lab'), ('other', 'Other')], default='other', help_text='FHIR category: vital sign, laboratory, survey, exam, or other grouping.', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='device',
            field=models.ForeignKey(blank=True, help_text='FHIR device: device that generated or was used for this observation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='effective_datetime',
            field=models.DateTimeField(blank=True, help_text='FHIR effective[x]: clinically relevant time for the observation.', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='interpretation',
            field=models.CharField(blank=True, help_text='FHIR interpretation: high, low, normal, abnormal, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='loinc_code',
            field=models.CharField(blank=True, help_text='FHIR code.coding: LOINC code when present.', max_length=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='name',
            field=models.CharField(help_text='FHIR code: observation name or test performed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional observation comments.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient the observation is about.', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='reference_range',
            field=models.CharField(blank=True, help_text='FHIR referenceRange: expected or normal range.', max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='specimen',
            field=models.ForeignKey(blank=True, help_text='FHIR specimen: specimen used for this observation or lab result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='clinical.specimen'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='unit',
            field=models.CharField(blank=True, help_text='FHIR valueQuantity.unit/code: unit for numeric result values.', max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='FHIR valueQuantity.value: numeric result value.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value_string',
            field=models.CharField(blank=True, help_text='FHIR valueString/valueCodeableConcept: textual result value.', max_length=255),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='authored_on',
            field=models.DateTimeField(blank=True, help_text='FHIR authoredOn: when the assessment was recorded.', null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='code',
            field=models.CharField(blank=True, help_text='FHIR code: type of risk being assessed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR basis: conditions used as evidence for the risk estimate.', related_name='risk_assessments', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='diagnostic_reports',
            field=models.ManyToManyField(blank=True, help_text='FHIR basis: diagnostic reports used as evidence for the risk estimate.', related_name='risk_assessments', to='clinical.diagnosticreport'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='FHIR encounter: visit or encounter associated with the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='clinical.encounter'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='method',
            field=models.CharField(blank=True, help_text='FHIR method: evaluation mechanism or algorithm used.', max_length=255),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='mitigation',
            field=models.TextField(blank=True, help_text='FHIR mitigation: how the risk may be reduced.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional risk assessment comments.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='observations',
            field=models.ManyToManyField(blank=True, help_text='FHIR basis: observations used as evidence for the risk estimate.', related_name='risk_assessments', to='clinical.observation'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='occurrence_datetime',
            field=models.DateTimeField(blank=True, help_text='FHIR occurrence[x]: when the assessment was performed.', null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient or group whose risk is assessed.', on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='performer_device',
            field=models.ForeignKey(blank=True, help_text='FHIR performer: device or system that performed the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_risk_assessments', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='performer_organization',
            field=models.ForeignKey(blank=True, help_text='FHIR performer: organization that performed the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_risk_assessments', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='performer_practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR performer: practitioner who performed the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_risk_assessments', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='performer_role',
            field=models.ForeignKey(blank=True, help_text='FHIR performer: practitioner role that performed the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_risk_assessments', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='prediction_summary',
            field=models.TextField(blank=True, help_text='FHIR prediction: outcome, probability, qualitative risk, timing, and rationale.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: registered, preliminary, final, amended, or entered-in-error.', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='accession_identifier',
            field=models.CharField(blank=True, help_text='FHIR accessionIdentifier: identifier assigned by lab or specimen processor.', max_length=100),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='body_site',
            field=models.CharField(blank=True, help_text='FHIR collection.bodySite: anatomical source of specimen.', max_length=255),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collected_datetime',
            field=models.DateTimeField(blank=True, help_text='FHIR collection.collected[x]: when the specimen was collected.', null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collection_method',
            field=models.CharField(blank=True, help_text='FHIR collection.method: how the specimen was collected.', max_length=255),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collector_display',
            field=models.CharField(blank=True, help_text='FHIR collection.collector: person or organization that collected the specimen.', max_length=255),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional specimen comments.'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='parent_specimens',
            field=models.ManyToManyField(blank=True, help_text='FHIR parent: parent specimens from which this specimen was derived.', related_name='child_specimens', to='clinical.specimen'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient or source the specimen was collected from.', on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='received_time',
            field=models.DateTimeField(blank=True, help_text='FHIR receivedTime: when the specimen was received for processing.', null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimen_type',
            field=models.CharField(blank=True, help_text='FHIR type: kind of specimen, such as blood, urine, or tissue.', max_length=255),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: available, unavailable, unsatisfactory, or entered-in-error.', max_length=30),
        ),
    ]
