# Generated by Django 4.2.4 on 2026-06-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_options'),
        ('clinical', '0014_alter_allergy_category_alter_allergy_criticality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careteamparticipant',
            name='care_team',
            field=models.ForeignKey(help_text='FHIR CareTeam.participant owner: care team this participant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='clinical.careteam'),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR participant.period.end: when participation ended.', null=True),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='location',
            field=models.ForeignKey(blank=True, help_text='FHIR participant.member: location participant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_team_participations', to='clinical.location'),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='member_display',
            field=models.CharField(blank=True, help_text='FHIR participant.member.display: imported participant display text.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='member_reference',
            field=models.CharField(blank=True, help_text='FHIR participant.member.reference: original FHIR member reference.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='on_behalf_of_display',
            field=models.CharField(blank=True, help_text='FHIR participant.onBehalfOf.display: organization represented by participant.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='on_behalf_of_reference',
            field=models.CharField(blank=True, help_text='FHIR participant.onBehalfOf.reference: original FHIR onBehalfOf reference.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='FHIR participant.member: organization participant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_team_participations', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR participant.member: practitioner participant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_team_participations', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='related_person',
            field=models.ForeignKey(blank=True, help_text='FHIR participant.member: related person participant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_team_participations', to='clinical.relatedperson'),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='role',
            field=models.CharField(blank=True, help_text='FHIR participant.role: role of this participant on the team.', max_length=255),
        ),
        migrations.AlterField(
            model_name='careteamparticipant',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR participant.period.start: when participation started.', null=True),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='care_manager_practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR careManager: practitioner coordinating the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_episodes', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='care_manager_role',
            field=models.ForeignKey(blank=True, help_text='FHIR careManager: practitioner role coordinating the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_episodes', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='care_teams',
            field=models.ManyToManyField(blank=True, help_text='FHIR team: care teams involved in this episode.', related_name='episodes_of_care', to='clinical.careteam'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='diagnosis_summary',
            field=models.TextField(blank=True, help_text='FHIR diagnosis: imported diagnosis/role/rank summary.'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR period.end: end of episode responsibility.', null=True),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='episode_type',
            field=models.CharField(blank=True, help_text='FHIR type: type of episode or care responsibility.', max_length=255),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='managing_organization',
            field=models.ForeignKey(blank=True, help_text='FHIR managingOrganization: organization with care responsibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes_of_care', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='notes',
            field=models.TextField(blank=True, help_text='Imported notes or source text for this episode of care.'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='patient',
            field=models.ForeignKey(help_text='FHIR patient: patient whose care is grouped into this episode.', on_delete=django.db.models.deletion.CASCADE, related_name='episodes_of_care', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='referral_requests',
            field=models.ManyToManyField(blank=True, help_text='FHIR referralRequest: referrals or requests initiating this episode.', related_name='episodes_of_care', to='clinical.servicerequest'),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR period.start: start of episode responsibility.', null=True),
        ),
        migrations.AlterField(
            model_name='episodeofcare',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: planned, waitlist, active, onhold, finished, cancelled, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='device',
            field=models.ForeignKey(blank=True, help_text='FHIR member.entity: device member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR member.period.end: when group membership ended.', null=True),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='entity_display',
            field=models.CharField(blank=True, help_text='FHIR member.entity.display: imported display text for unresolved members.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='entity_reference',
            field=models.CharField(blank=True, help_text='FHIR member.entity.reference: original FHIR reference string.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='group',
            field=models.ForeignKey(help_text='FHIR Group.member owner: group this member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='clinical.fhirgroup'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='inactive',
            field=models.BooleanField(blank=True, help_text='FHIR member.inactive: whether this member is inactive in the group.', null=True),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='medication',
            field=models.ForeignKey(blank=True, help_text='FHIR member.entity: medication member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.medication'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='member_group',
            field=models.ForeignKey(blank=True, help_text='FHIR member.entity: nested group member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_group_memberships', to='clinical.fhirgroup'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='FHIR member.entity: patient member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR member.entity: practitioner member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='practitioner_role',
            field=models.ForeignKey(blank=True, help_text='FHIR member.entity: practitioner role member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='fhirgroupmember',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR member.period.start: when group membership started.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='FHIR address: physical address of the location.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, help_text='FHIR telecom: email contact.', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, help_text='FHIR type: kind of location, such as clinic, ward, room, or vehicle.', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='managing_organization',
            field=models.CharField(blank=True, help_text='FHIR managingOrganization: organization responsible for the location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='mode',
            field=models.CharField(blank=True, help_text='FHIR mode: instance or kind.', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='FHIR name: location name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, help_text='Imported notes or source text for this location.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, help_text='FHIR telecom: phone contact.', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: active, suspended, or inactive.', max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, help_text="FHIR active: whether this organization's record is active."),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, help_text='FHIR address: organization address.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='FHIR telecom: email contact.', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='FHIR name: organization name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, help_text='Imported notes or source text for this organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, help_text='FHIR type: kind of organization, such as provider, department, team, or payer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, help_text='FHIR telecom: phone contact.', max_length=30),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='linked_person',
            field=models.ForeignKey(blank=True, help_text='FHIR link.target: another Person resource linked to this identity record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_person_records', to='clinical.person'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='FHIR link.target: Patient resource believed to represent the same actual person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identity_links', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='person',
            field=models.ForeignKey(help_text='FHIR Person.link owner: shared Person identity record.', on_delete=django.db.models.deletion.CASCADE, related_name='link_records', to='clinical.person'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR link.target: Practitioner resource believed to represent the same actual person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identity_links', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='related_person',
            field=models.ForeignKey(blank=True, help_text='FHIR link.target: RelatedPerson resource believed to represent the same actual person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_identity_links', to='clinical.relatedperson'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='target_display',
            field=models.CharField(blank=True, help_text='FHIR link.target.display: imported display text for unresolved targets.', max_length=255),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='target_reference',
            field=models.CharField(blank=True, help_text='FHIR link.target.reference: original FHIR reference string.', max_length=255),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='active',
            field=models.BooleanField(default=True, help_text='FHIR active: whether the practitioner record is in active use.'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='address',
            field=models.TextField(blank=True, help_text='FHIR address: practitioner address.'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='email',
            field=models.EmailField(blank=True, help_text='FHIR telecom: email contact.', max_length=254),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='name',
            field=models.CharField(help_text='FHIR name: practitioner name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='notes',
            field=models.TextField(blank=True, help_text='Imported notes or source text for this practitioner.'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='npi',
            field=models.CharField(blank=True, help_text='FHIR identifier: National Provider Identifier when present.', max_length=30),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='phone',
            field=models.CharField(blank=True, help_text='FHIR telecom: phone contact.', max_length=30),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='qualification',
            field=models.CharField(blank=True, help_text='FHIR qualification.code: professional qualification or credential.', max_length=255),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='active',
            field=models.BooleanField(default=True, help_text='FHIR active: whether this role is active.'),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='email',
            field=models.EmailField(blank=True, help_text='FHIR telecom: email contact for this role.', max_length=254),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='end_date',
            field=models.DateField(blank=True, help_text='FHIR period.end: when this role stopped being valid.', null=True),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='FHIR location: locations where this role is available.', related_name='practitioner_roles', to='clinical.location'),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='notes',
            field=models.TextField(blank=True, help_text='Imported notes or source text for this practitioner role.'),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='FHIR organization: organization where the role applies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_roles', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='phone',
            field=models.CharField(blank=True, help_text='FHIR telecom: phone contact for this role.', max_length=30),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR practitioner: practitioner who can perform this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='role',
            field=models.CharField(blank=True, help_text='FHIR code: role performed by the practitioner.', max_length=255),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='specialty',
            field=models.CharField(blank=True, help_text='FHIR specialty: specific specialty of the practitioner in this role.', max_length=255),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='start_date',
            field=models.DateField(blank=True, help_text='FHIR period.start: when this role became valid.', null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='body_site',
            field=models.CharField(blank=True, help_text='FHIR bodySite: anatomical site where procedure was performed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='care_plans',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn/partOf: care plans related to the procedure.', related_name='procedures', to='clinical.careplan'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='category',
            field=models.CharField(blank=True, help_text='FHIR category: broad classification of procedure.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: conditions that explain why the procedure was performed.', related_name='procedures', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='FHIR encounter: encounter associated with the procedure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='clinical.encounter'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='location_display',
            field=models.CharField(blank=True, help_text='FHIR location: where procedure was performed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(help_text='FHIR code: procedure performed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional procedure comments.'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='outcome',
            field=models.CharField(blank=True, help_text='FHIR outcome: result of the procedure.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient the procedure was performed on.', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='performed_end',
            field=models.DateTimeField(blank=True, help_text='FHIR performedPeriod.end: end time when a period is used.', null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='performed_start',
            field=models.DateTimeField(blank=True, help_text='FHIR performed[x]: start or occurrence time.', null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='reason',
            field=models.CharField(blank=True, help_text='FHIR reasonCode: coded reason for procedure.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='service_requests',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn: service requests fulfilled by the procedure.', related_name='procedures', to='clinical.servicerequest'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: preparation, in-progress, completed, stopped, entered-in-error, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='actor_display',
            field=models.CharField(blank=True, help_text='FHIR performer.actor.display: imported performer display text.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='actor_reference',
            field=models.CharField(blank=True, help_text='FHIR performer.actor.reference: original FHIR actor reference.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='on_behalf_of_display',
            field=models.CharField(blank=True, help_text='FHIR performer.onBehalfOf.display: organization represented by actor.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='on_behalf_of_reference',
            field=models.CharField(blank=True, help_text='FHIR performer.onBehalfOf.reference: original FHIR onBehalfOf reference.', max_length=255),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='FHIR performer.actor/onBehalfOf: organization involved in the procedure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_performances', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR performer.actor: practitioner who performed the procedure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_performances', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='procedure',
            field=models.ForeignKey(help_text='FHIR Procedure.performer owner: procedure this performer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='performer_links', to='clinical.procedure'),
        ),
        migrations.AlterField(
            model_name='procedureperformer',
            name='role',
            field=models.CharField(blank=True, help_text='FHIR performer.function: role or function of the performer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='authored_on',
            field=models.DateTimeField(blank=True, help_text='FHIR authoredOn: when the request was signed or authored.', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='care_plans',
            field=models.ManyToManyField(blank=True, help_text='FHIR basedOn: care plans this request fulfills or follows.', related_name='service_requests', to='clinical.careplan'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(blank=True, help_text='FHIR category: classification of service requested.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='FHIR reasonReference: conditions supporting the request.', related_name='service_requests', to='clinical.condition'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='do_not_perform',
            field=models.BooleanField(default=False, help_text='FHIR doNotPerform: true when this is a request not to perform the service.'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='FHIR encounter: encounter where the request was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='clinical.encounter'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='intent',
            field=models.CharField(blank=True, help_text='FHIR intent: proposal, plan, directive, order, original-order, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location_code',
            field=models.CharField(blank=True, help_text='FHIR locationCode: coded requested location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='FHIR locationReference: requested service locations.', related_name='service_requests', to='clinical.location'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(help_text='FHIR code: service, order, procedure, or diagnostic request.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='FHIR note: additional service request comments.'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='occurrence_end',
            field=models.DateTimeField(blank=True, help_text='FHIR occurrencePeriod.end: requested end time when a period is used.', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='occurrence_start',
            field=models.DateTimeField(blank=True, help_text='FHIR occurrence[x]: requested start or occurrence time.', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='patient',
            field=models.ForeignKey(help_text='FHIR subject: patient the service is requested for.', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='patient_instruction',
            field=models.TextField(blank=True, help_text='FHIR patientInstruction: instructions for the patient.'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performer_type',
            field=models.CharField(blank=True, help_text='FHIR performerType: requested performer type.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performers_care_teams',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: care teams asked to perform the service.', related_name='service_requests', to='clinical.careteam'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performers_devices',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: devices asked to perform the service.', related_name='service_request_performances', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performers_organizations',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: organizations asked to perform the service.', related_name='service_request_performances', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performers_practitioners',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: practitioners asked to perform the service.', related_name='service_request_performances', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performers_roles',
            field=models.ManyToManyField(blank=True, help_text='FHIR performer: practitioner roles asked to perform the service.', related_name='service_request_performances', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(blank=True, help_text='FHIR priority: routine, urgent, asap, or stat.', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reason',
            field=models.CharField(blank=True, help_text='FHIR reasonCode: coded reason for the request.', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='replaces',
            field=models.ManyToManyField(blank=True, help_text='FHIR replaces: service requests replaced by this one.', related_name='replacement_requests', to='clinical.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester_device',
            field=models.ForeignKey(blank=True, help_text='FHIR requester: device or system that requested the service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_services', to='clinical.device'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester_organization',
            field=models.ForeignKey(blank=True, help_text='FHIR requester: organization that requested the service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_services', to='clinical.organization'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester_practitioner',
            field=models.ForeignKey(blank=True, help_text='FHIR requester: practitioner who requested the service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_services', to='clinical.practitioner'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester_role',
            field=models.ForeignKey(blank=True, help_text='FHIR requester: practitioner role that requested the service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_services', to='clinical.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='specimens',
            field=models.ManyToManyField(blank=True, help_text='FHIR specimen: specimens relevant to the request.', related_name='service_requests', to='clinical.specimen'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, help_text='FHIR status: draft, active, on-hold, revoked, completed, entered-in-error, or unknown.', max_length=30),
        ),
    ]
