# Generated by Django 4.2.4 on 2026-06-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        (
            "documents",
            "0002_clinicaldocument_authors_clinicaldocument_custodian_and_more",
        ),
        ("clinical", "0016_medicationcatalog_questionnaireresponse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: coverage category such as medical, dental, vision, accident, or self-pay.",
                        max_length=255,
                    ),
                ),
                (
                    "subscriber_id",
                    models.CharField(
                        blank=True,
                        help_text="FHIR subscriberId: insurer-assigned subscriber identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "dependent",
                    models.CharField(
                        blank=True,
                        help_text="FHIR dependent: dependent number under the coverage.",
                        max_length=255,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="FHIR relationship: beneficiary relationship to subscriber.",
                        max_length=255,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.start: coverage start date.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.end: coverage end date.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FHIR order: relative coordination order for active coverages.",
                        null=True,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="FHIR network: insurer-defined network name or identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "class_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR class: group, plan, subgroup, class, and other insurer classifications.",
                    ),
                ),
                (
                    "cost_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR costToBeneficiary: copay, deductible, coinsurance, and related patient cost details.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this coverage.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coverage",
                "verbose_name_plural": "Coverages",
            },
        ),
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="FHIR name: official plan or product name.",
                        max_length=255,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="FHIR alias: alternate plan names.",
                        max_length=255,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: kind of insurance plan or product.",
                        max_length=255,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.start: when the plan is available or effective.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.end: when the plan availability/effectiveness ends.",
                        null=True,
                    ),
                ),
                (
                    "coverage_area",
                    models.TextField(
                        blank=True,
                        help_text="FHIR coverageArea: geographic areas covered by the plan.",
                    ),
                ),
                (
                    "contact_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR contact/telecom: plan contact details.",
                    ),
                ),
                (
                    "benefit_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR coverage/plan.specificCost/benefit: summarized benefits and plan cost details.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this insurance plan.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR administeredBy: organization that administers the plan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_insurance_plans",
                        to="clinical.organization",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR ownedBy: organization that is legally responsible for the plan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_insurance_plans",
                        to="clinical.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Plan",
                "verbose_name_plural": "Insurance Plans",
            },
        ),
        migrations.CreateModel(
            name="ExplanationOfBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "eob_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: EOB/claim category such as institutional, oral, pharmacy, professional, or vision.",
                        max_length=255,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        help_text="FHIR use: claim, preauthorization, predetermination, or other use.",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="FHIR outcome: queued, complete, error, partial, or other adjudication result.",
                        max_length=255,
                    ),
                ),
                (
                    "disposition",
                    models.TextField(
                        blank=True,
                        help_text="FHIR disposition: human-readable processing result.",
                    ),
                ),
                (
                    "billable_period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR billablePeriod.start: service billing period start.",
                        null=True,
                    ),
                ),
                (
                    "billable_period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR billablePeriod.end: service billing period end.",
                        null=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: when the EOB was created.",
                        null=True,
                    ),
                ),
                (
                    "total_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR total: benefit, allowed, submitted, patient responsibility, and payment totals.",
                    ),
                ),
                (
                    "diagnosis_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR diagnosis: diagnosis sequence, code, and package details.",
                    ),
                ),
                (
                    "item_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR item: adjudicated service/product line item details.",
                    ),
                ),
                (
                    "payment_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR payment: payment type, amount, date, and payee details.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="FHIR processNote or imported source notes.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coverages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR insurance.coverage: insurance coverages used in adjudication.",
                        related_name="explanation_of_benefits",
                        to="clinical.coverage",
                    ),
                ),
                (
                    "encounters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR item.encounter: encounters associated with adjudicated line items.",
                        related_name="explanation_of_benefits",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR insurer: insurer responsible for the benefit statement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="explanation_of_benefits",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="FHIR patient: patient receiving products or services.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation_of_benefits",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "provider_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR provider: organization responsible for services when resolved locally.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_explanation_of_benefits",
                        to="clinical.organization",
                    ),
                ),
                (
                    "provider_practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR provider: practitioner responsible for services when resolved locally.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="explanation_of_benefits",
                        to="clinical.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation of Benefit",
                "verbose_name_plural": "Explanations of Benefits",
            },
        ),
        migrations.AddField(
            model_name="coverage",
            name="insurer_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="FHIR insurancePlan extension/reference when resolved locally.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coverages",
                to="clinical.insuranceplan",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="patient",
            field=models.ForeignKey(
                help_text="FHIR beneficiary: patient covered by the policy or payment agreement.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="patients.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="payor_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="FHIR payor: insurer or organization issuing the coverage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coverages_as_payor",
                to="clinical.organization",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="policy_holder_patient",
            field=models.ForeignKey(
                blank=True,
                help_text="FHIR policyHolder: patient who owns the policy, when applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_coverages",
                to="patients.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="subscriber_patient",
            field=models.ForeignKey(
                blank=True,
                help_text="FHIR subscriber: patient who subscribed to the policy, when applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscribed_coverages",
                to="patients.patientprofile",
            ),
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, proposed, active, rejected, inactive, entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="FHIR scope: privacy, treatment, research, advance care planning, or other consent scope.",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: consent category such as treatment, information access, or procedure consent.",
                        max_length=255,
                    ),
                ),
                (
                    "policy_rule",
                    models.CharField(
                        blank=True,
                        help_text="FHIR policyRule: regulation or policy basis for the consent.",
                        max_length=255,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR provision.period.start: when consent permission/denial becomes effective.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR provision.period.end: when consent permission/denial ends.",
                        null=True,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        help_text="FHIR provision.type: permit or deny.",
                        max_length=30,
                    ),
                ),
                (
                    "provision_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR provision: actors, actions, classes, codes, purposes, and periods.",
                    ),
                ),
                (
                    "verification_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR verification: verification status, verifier, and verification date.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this consent.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR organization: organization that manages or witnesses the consent.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="FHIR patient: patient or person whose consent is described.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "performer_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR performer: practitioners who granted, acknowledged, or witnessed the consent.",
                        related_name="performed_consents",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "questionnaire_responses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Local link: questionnaire responses used as consent/intake evidence.",
                        related_name="consents",
                        to="clinical.questionnaireresponse",
                    ),
                ),
                (
                    "related_immunizations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Local link: vaccine records associated with this consent when source references can be resolved.",
                        related_name="consents",
                        to="clinical.immunization",
                    ),
                ),
                (
                    "source_documents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR source[x]: signed or source documents for the consent.",
                        related_name="consents",
                        to="documents.clinicaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent",
                "verbose_name_plural": "Consents",
            },
        ),
    ]
