# Generated by Django 4.2.4 on 2026-06-20 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        ("clinical", "0018_visionprescription_supplyrequest_supplydelivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: proposed, pending, booked, arrived, fulfilled, cancelled, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "cancelation_reason",
                    models.CharField(
                        blank=True,
                        help_text="FHIR cancelationReason: reason appointment was cancelled.",
                        max_length=255,
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR serviceCategory: broad service category.",
                        max_length=255,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR serviceType: specific service type.",
                        max_length=255,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR appointmentType: type/style of appointment.",
                        max_length=255,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="FHIR reasonCode: reason for appointment.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: appointment description.",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR start: appointment start instant.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR end: appointment end instant.",
                        null=True,
                    ),
                ),
                (
                    "minutes_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FHIR minutesDuration: expected duration in minutes.",
                        null=True,
                    ),
                ),
                (
                    "participant_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR participant: participant statuses and displays.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="FHIR comment/patientInstruction: appointment comments or patient instructions.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "based_on_service_requests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR basedOn: service requests fulfilled by appointment.",
                        related_name="appointments",
                        to="clinical.servicerequest",
                    ),
                ),
                (
                    "participants_locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR participant.actor: location participants.",
                        related_name="appointments",
                        to="clinical.location",
                    ),
                ),
                (
                    "participants_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR participant.actor: practitioner participants.",
                        related_name="appointments",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR participant.actor: patient participant when present.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, suspended, error, off, entered-in-error, or test.",
                        max_length=30,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR connectionType: protocol/profile used by the endpoint.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: endpoint name.",
                        max_length=255,
                    ),
                ),
                (
                    "payload_type",
                    models.TextField(
                        blank=True,
                        help_text="FHIR payloadType: payload types supported.",
                    ),
                ),
                (
                    "payload_mime_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR payloadMimeType: MIME types supported.",
                        max_length=255,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="FHIR address: technical endpoint address.",
                    ),
                ),
                (
                    "header_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR header: headers required by endpoint.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this endpoint.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managing_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR managingOrganization: organization that manages the endpoint.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endpoints",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthcareService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="FHIR active: whether this service record is active.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: broad service category.",
                        max_length=255,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: specific service type.",
                        max_length=255,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="FHIR specialty: specialty that performs the service.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="FHIR name: healthcare service name.", max_length=255
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="FHIR comment: extra details about the service.",
                    ),
                ),
                (
                    "telecom",
                    models.TextField(
                        blank=True, help_text="FHIR telecom: service contact details."
                    ),
                ),
                (
                    "availability_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR availableTime/notAvailable: service availability.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this healthcare service.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoints",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR endpoint: technical endpoints for the service.",
                        related_name="healthcare_services",
                        to="clinical.endpoint",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR location: locations where service is available.",
                        related_name="healthcare_services",
                        to="clinical.location",
                    ),
                ),
                (
                    "provided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR providedBy: organization providing the service.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="healthcare_services",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="FHIR active: whether schedule is active.",
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR serviceCategory: broad service category.",
                        max_length=255,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR serviceType: specific service type.",
                        max_length=255,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="FHIR specialty: specialty for schedule.",
                        max_length=255,
                    ),
                ),
                (
                    "planning_horizon_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR planningHorizon.start: schedule planning start.",
                        null=True,
                    ),
                ),
                (
                    "planning_horizon_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR planningHorizon.end: schedule planning end.",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="FHIR comment: comments about availability.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actors_healthcare_services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR actor: healthcare service actors.",
                        related_name="schedules",
                        to="clinical.healthcareservice",
                    ),
                ),
                (
                    "actors_locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR actor: location actors.",
                        related_name="schedules",
                        to="clinical.location",
                    ),
                ),
                (
                    "actors_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR actor: practitioner actors.",
                        related_name="schedules",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR actor: patient actor when the schedule is for a patient.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, inactive, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: substance category.",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR code: substance code or name.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="FHIR description: substance description."
                    ),
                ),
                (
                    "instance_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR instance: batch, quantity, and expiry details.",
                    ),
                ),
                (
                    "ingredient_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR ingredient: component substances and quantities.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this substance.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, requested, accepted, in-progress, completed, failed, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="FHIR intent: unknown, proposal, plan, order, original-order, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="FHIR priority: routine, urgent, asap, or stat.",
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="FHIR code: task type.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="FHIR description: task description."
                    ),
                ),
                (
                    "authored_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR authoredOn: when task was created.",
                        null=True,
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR lastModified: when task was last changed.",
                        null=True,
                    ),
                ),
                (
                    "execution_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR executionPeriod.start: task execution start.",
                        null=True,
                    ),
                ),
                (
                    "execution_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR executionPeriod.end: task execution end.",
                        null=True,
                    ),
                ),
                (
                    "input_summary",
                    models.TextField(
                        blank=True, help_text="FHIR input: task input parameters."
                    ),
                ),
                (
                    "output_summary",
                    models.TextField(
                        blank=True, help_text="FHIR output: task output parameters."
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="FHIR note: task comments."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "based_on_service_requests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR basedOn: requests this task fulfills.",
                        related_name="tasks",
                        to="clinical.servicerequest",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR encounter: healthcare event associated with the task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "owner_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR owner: organization responsible for task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_tasks",
                        to="clinical.organization",
                    ),
                ),
                (
                    "owner_practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR owner: practitioner responsible for task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_tasks",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR for/focus context: patient associated with the task when known.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: busy, free, busy-unavailable, busy-tentative, entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR serviceCategory: broad service category.",
                        max_length=255,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR serviceType: specific service type.",
                        max_length=255,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="FHIR specialty: specialty for slot.",
                        max_length=255,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR appointmentType: style of appointment.",
                        max_length=255,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR start: slot start instant.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="FHIR end: slot end instant.", null=True
                    ),
                ),
                (
                    "overbooked",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR overbooked: whether slot has overbooked appointments.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="FHIR comment: comments on slot."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR schedule: schedule this slot belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="clinical.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR target: resources this provenance statement describes.",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        help_text="FHIR activity: activity that occurred.",
                        max_length=255,
                    ),
                ),
                (
                    "occurred_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR occurred[x]: when the activity started or occurred.",
                        null=True,
                    ),
                ),
                (
                    "occurred_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR occurredPeriod.end: when the activity ended.",
                        null=True,
                    ),
                ),
                (
                    "recorded",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR recorded: when the activity was recorded.",
                        null=True,
                    ),
                ),
                (
                    "policy",
                    models.TextField(
                        blank=True,
                        help_text="FHIR policy: policies or plans defining the activity.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="FHIR reason: reason the activity occurred.",
                        max_length=255,
                    ),
                ),
                (
                    "agent_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR agent: people, organizations, systems, or devices involved.",
                    ),
                ),
                (
                    "entity_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR entity: source or derived entities used in the activity.",
                    ),
                ),
                (
                    "signature_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR signature: digital signatures on the provenance target.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this provenance record.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR location: where the activity occurred.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provenance_records",
                        to="clinical.location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR patient compartment: patient associated with the provenance targets or agents, when known.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance_records",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provenance",
                "verbose_name_plural": "Provenance",
            },
        ),
        migrations.CreateModel(
            name="OrganizationAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="FHIR active: whether this affiliation is active.",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.start: affiliation start date.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.end: affiliation end date.",
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="FHIR code: role played by the participating organization.",
                        max_length=255,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="FHIR specialty: specific specialty in this role.",
                        max_length=255,
                    ),
                ),
                (
                    "telecom",
                    models.TextField(
                        blank=True,
                        help_text="FHIR telecom: contact details relevant to this affiliation.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this organization affiliation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoints",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR endpoint: technical endpoints for this affiliation.",
                        related_name="organization_affiliations",
                        to="clinical.endpoint",
                    ),
                ),
                (
                    "healthcare_services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR healthcareService: services provided through this affiliation.",
                        related_name="organization_affiliations",
                        to="clinical.healthcareservice",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR location: locations for this affiliation.",
                        related_name="organization_affiliations",
                        to="clinical.location",
                    ),
                ),
                (
                    "networks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR network: provider networks for this affiliation.",
                        related_name="network_affiliations",
                        to="clinical.organization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR organization: primary organization where role is available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliations",
                        to="clinical.organization",
                    ),
                ),
                (
                    "participating_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR participatingOrganization: organization providing/performing the role.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participating_affiliations",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="FHIR source: source system/application/actor.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: current, superseded, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "manifest_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: kind of document set.",
                        max_length=255,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR created: when the manifest was created.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: human-readable manifest description.",
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR content: document references included in the manifest.",
                    ),
                ),
                (
                    "related_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR related: related identifiers or resources.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this document manifest.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR author: practitioner who authored the manifest.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_manifests",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR subject: patient or subject of documents in the manifest.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_manifests",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        help_text="FHIR type: metric identity, such as heart rate or PEEP setting.",
                        max_length=255,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="FHIR unit: unit of measure for this metric.",
                        max_length=255,
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR operationalStatus: on, off, standby, entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="FHIR color: display color for the metric.",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: measurement, setting, calculation, or unspecified.",
                        max_length=30,
                    ),
                ),
                (
                    "calibration_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR calibration: type, state, and time of calibration.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this device metric.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR parent: parent device/component.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_metrics",
                        to="clinical.device",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR source: device this metric belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_metrics",
                        to="clinical.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: preliminary, final, amended, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "composition_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: kind of composition/document.",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: categorization of composition.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-readable composition title.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: when composition was edited.",
                        null=True,
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        blank=True,
                        help_text="FHIR confidentiality: confidentiality code.",
                        max_length=30,
                    ),
                ),
                (
                    "section_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR section: section titles, codes, text, and entries.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this composition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR author: practitioner authors.",
                        related_name="authored_compositions",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR custodian: organization maintaining the composition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compositions",
                        to="clinical.organization",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR encounter: clinical encounter associated with the composition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compositions",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR subject: patient or subject of the composition.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinaryResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="FHIR contentType: MIME type of the binary content.",
                        max_length=255,
                    ),
                ),
                (
                    "security_context",
                    models.CharField(
                        blank=True,
                        help_text="FHIR securityContext: resource whose access rules apply.",
                        max_length=255,
                    ),
                ),
                (
                    "data_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FHIR data: decoded byte count when inline data was supplied.",
                        null=True,
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(
                        blank=True,
                        help_text="FHIR data: SHA-256 hash of decoded inline binary content.",
                        max_length=64,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this binary resource.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Local patient association when binary content can be tied to a patient.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binary_resources",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Binary Resource",
                "verbose_name_plural": "Binary Resources",
            },
        ),
        migrations.CreateModel(
            name="AppointmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR participantStatus: accepted, declined, tentative, needs-action.",
                        max_length=30,
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR participantType: role of participant.",
                        max_length=255,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR start: proposed/actual participant start.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR end: proposed/actual participant end.",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="FHIR comment: participant response comment.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR actor: location actor when location responds.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_responses",
                        to="clinical.location",
                    ),
                ),
                (
                    "actor_practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR actor: practitioner actor when practitioner responds.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_responses",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR appointment: appointment being responded to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="clinical.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR actor: patient actor when patient responds.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_responses",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="slots",
            field=models.ManyToManyField(
                blank=True,
                help_text="FHIR slot: slots that provide availability.",
                related_name="appointments",
                to="clinical.slot",
            ),
        ),
    ]
