# Generated by Django 4.2.4 on 2026-06-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        ("clinical", "0019_appointment_endpoint_healthcareservice_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, inactive, entered-in-error, or on-hold.",
                        max_length=30,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: categorization of the account.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: human-readable account name.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="FHIR description: account description."
                    ),
                ),
                (
                    "service_period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR servicePeriod.start: start of account coverage/service dates.",
                        null=True,
                    ),
                ),
                (
                    "service_period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR servicePeriod.end: end of account coverage/service dates.",
                        null=True,
                    ),
                ),
                (
                    "guarantor_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR guarantor: parties responsible for account balances.",
                    ),
                ),
                (
                    "balance_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR balance: account balances by term/type.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this account.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coverages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR coverage.coverage: insurance coverages associated with the account.",
                        related_name="accounts",
                        to="clinical.coverage",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR owner: organization responsible for tracking the account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_accounts",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR subject: patient or other party the account tracks.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: category of claim, such as institutional, oral, pharmacy, or professional.",
                        max_length=255,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        help_text="FHIR use: claim, preauthorization, predetermination, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="FHIR priority: desired processing priority.",
                        max_length=255,
                    ),
                ),
                (
                    "billable_period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR billablePeriod.start: beginning of service billing period.",
                        null=True,
                    ),
                ),
                (
                    "billable_period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR billablePeriod.end: end of service billing period.",
                        null=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: claim creation date.",
                        null=True,
                    ),
                ),
                (
                    "diagnosis_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR diagnosis: diagnosis codes or references on the claim.",
                    ),
                ),
                (
                    "item_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR item: claim line items, products/services, quantities, and net amounts.",
                    ),
                ),
                (
                    "insurance_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR insurance: claim insurance sequence, focal status, and coverage displays.",
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True,
                        help_text="FHIR total: total claim amount.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this claim.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coverages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR insurance.coverage: coverages used for this claim.",
                        related_name="claims",
                        to="clinical.coverage",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR insurer: target insurer for adjudication.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims_as_insurer",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR patient: patient receiving products or services.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "provider_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR provider: organization responsible for the claim when present.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims_as_provider",
                        to="clinical.organization",
                    ),
                ),
                (
                    "provider_practitioner",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR provider: practitioner responsible for the claim when present.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims_as_provider",
                        to="clinical.practitioner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: observation category.",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR code: type of observation being defined.",
                        max_length=255,
                    ),
                ),
                (
                    "permitted_data_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR permittedDataType: allowed observation value data types.",
                        max_length=255,
                    ),
                ),
                (
                    "multiple_results_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR multipleResultsAllowed: whether multiple results are allowed.",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="FHIR method: method used to produce the observation.",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_report_name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR preferredReportName: preferred report display name.",
                        max_length=255,
                    ),
                ),
                (
                    "quantitative_details",
                    models.TextField(
                        blank=True,
                        help_text="FHIR quantitativeDetails: measurement unit, decimal precision, and conversion details.",
                    ),
                ),
                (
                    "qualified_interval_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR qualifiedInterval: reference ranges/intervals.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this observation definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this questionnaire.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the questionnaire.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly questionnaire name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly questionnaire title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for publication.",
                        max_length=255,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR subjectType: resource types the questionnaire can apply to.",
                        max_length=255,
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR approvalDate: when questionnaire was approved.",
                        null=True,
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR lastReviewDate: when questionnaire was last reviewed.",
                        null=True,
                    ),
                ),
                (
                    "effective_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR effectivePeriod.start: beginning of questionnaire effective period.",
                        null=True,
                    ),
                ),
                (
                    "effective_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR effectivePeriod.end: end of questionnaire effective period.",
                        null=True,
                    ),
                ),
                (
                    "item_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR item: questionnaire questions/groups.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this questionnaire.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, administratively-completed, approved, closed-to-accrual, completed, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="FHIR title: human-readable study title.",
                        max_length=255,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        help_text="FHIR phase: phase of the study.",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: study category.",
                        max_length=255,
                    ),
                ),
                (
                    "focus",
                    models.TextField(
                        blank=True,
                        help_text="FHIR focus: drugs, devices, conditions, or other focus codes.",
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="FHIR condition: conditions being studied.",
                    ),
                ),
                (
                    "contact_summary",
                    models.TextField(
                        blank=True, help_text="FHIR contact: study contact details."
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.start: study start date.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.end: study end date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="FHIR description: study description."
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="FHIR note: study notes."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR principalInvestigator: investigator responsible for the study.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_studies",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR site: locations where the study is conducted.",
                        related_name="research_studies",
                        to="clinical.location",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR sponsor: organization responsible for study initiation/management.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_research_studies",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: candidate, eligible, follow-up, ineligible, on-study, withdrawn, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.start: participation start date.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.end: participation end date.",
                        null=True,
                    ),
                ),
                (
                    "assigned_arm",
                    models.CharField(
                        blank=True,
                        help_text="FHIR assignedArm: study arm assigned to subject.",
                        max_length=255,
                    ),
                ),
                (
                    "actual_arm",
                    models.CharField(
                        blank=True,
                        help_text="FHIR actualArm: study arm actually followed.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this research subject.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR consent: consent record for study participation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_subjects",
                        to="clinical.consent",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="FHIR individual: patient participating in the research study.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_subjects",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR study: research study this subject participates in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="clinical.researchstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, issued, balanced, cancelled, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        blank=True, help_text="FHIR type: invoice type.", max_length=255
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: when the invoice was issued.",
                        null=True,
                    ),
                ),
                (
                    "participant_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR participant: parties involved in invoice creation or processing.",
                    ),
                ),
                (
                    "line_item_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR lineItem: charges included in the invoice.",
                    ),
                ),
                (
                    "total_net",
                    models.CharField(
                        blank=True,
                        help_text="FHIR totalNet: net invoice amount.",
                        max_length=255,
                    ),
                ),
                (
                    "total_gross",
                    models.CharField(
                        blank=True,
                        help_text="FHIR totalGross: gross invoice amount.",
                        max_length=255,
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="FHIR paymentTerms: payment timing or terms.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="FHIR note: invoice notes."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR account: account that tracks this invoice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="clinical.account",
                    ),
                ),
                (
                    "issuer_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR issuer: organization issuing the invoice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invoices",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR subject/recipient: patient associated with the invoice when present.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR deviceName.name: device name.",
                        max_length=255,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: type of device.",
                        max_length=255,
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True,
                        help_text="FHIR modelNumber: manufacturer model number.",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: device version.",
                        max_length=255,
                    ),
                ),
                (
                    "udi_device_identifier",
                    models.CharField(
                        blank=True,
                        help_text="FHIR udiDeviceIdentifier: device identifier details.",
                        max_length=255,
                    ),
                ),
                (
                    "specialization_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR specialization: standards/specializations supported.",
                    ),
                ),
                (
                    "property_summary",
                    models.TextField(
                        blank=True, help_text="FHIR property: device properties."
                    ),
                ),
                (
                    "capability_summary",
                    models.TextField(
                        blank=True, help_text="FHIR capability: device capabilities."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this device definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR manufacturer[x]: organization responsible for the device definition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_definitions",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClaimResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: claim response category.",
                        max_length=255,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        help_text="FHIR use: claim, preauthorization, predetermination, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="FHIR outcome: queued, complete, error, or partial.",
                        max_length=30,
                    ),
                ),
                (
                    "disposition",
                    models.TextField(
                        blank=True,
                        help_text="FHIR disposition: disposition message from adjudication.",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: response creation date.",
                        null=True,
                    ),
                ),
                (
                    "item_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR item/addItem: adjudication line summary.",
                    ),
                ),
                (
                    "total_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR total: adjudication totals by category.",
                    ),
                ),
                (
                    "payment_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR payment: payment type, amount, and date.",
                    ),
                ),
                (
                    "error_summary",
                    models.TextField(
                        blank=True, help_text="FHIR error: adjudication errors."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this claim response.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR insurer: party responsible for adjudication.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claim_responses",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR patient: patient associated with the claim response.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_responses",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "request_claim",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR request: claim this response adjudicates.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="clinical.claim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: planned, billable, not-billable, aborted, billed, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="FHIR code: charge item code.", max_length=255
                    ),
                ),
                (
                    "occurrence_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR occurrence[x]: when charge item occurred.",
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        help_text="FHIR quantity: quantity of service/product.",
                        max_length=255,
                    ),
                ),
                (
                    "factor_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="FHIR factorOverride: multiplying factor override.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_override",
                    models.CharField(
                        blank=True,
                        help_text="FHIR priceOverride: price override.",
                        max_length=255,
                    ),
                ),
                (
                    "total_price_component",
                    models.TextField(
                        blank=True,
                        help_text="FHIR totalPriceComponent: total price components.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="FHIR reason: coded reason for charge.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="FHIR note: charge comments."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR account: account this charge belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charge_items",
                        to="clinical.account",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR context: encounter associated with the charge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charge_items",
                        to="clinical.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR subject: patient associated with the charge.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_items",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "performer_practitioners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR performer.actor: practitioners involved with the charge.",
                        related_name="charge_items",
                        to="clinical.practitioner",
                    ),
                ),
                (
                    "service_requests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="FHIR service: service requests represented by this charge.",
                        related_name="charge_items",
                        to="clinical.servicerequest",
                    ),
                ),
            ],
        ),
    ]
