# Generated by Django 4.2.4 on 2026-06-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        ("clinical", "0020_account_claim_observationdefinition_questionnaire_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR recorded: when the activity was recorded.",
                        null=True,
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: identifier for the category of event.",
                        max_length=255,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        help_text="FHIR subtype: more specific event type.",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="FHIR action: create, read, update, delete, execute, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="FHIR outcome: success, minor failure, serious failure, or major failure.",
                        max_length=30,
                    ),
                ),
                (
                    "outcome_description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR outcomeDesc: description of the outcome.",
                    ),
                ),
                (
                    "agent_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR agent: people, systems, or organizations involved in the event.",
                    ),
                ),
                (
                    "source_observer",
                    models.CharField(
                        blank=True,
                        help_text="FHIR source.observer: system or actor reporting the event.",
                        max_length=255,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR source.type: type of audit source.",
                        max_length=255,
                    ),
                ),
                (
                    "entity_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR entity: data or objects involved in the event.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this audit event.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Local patient association when the audit event references a patient.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
    ]
