# Generated by Django 4.2.4 on 2026-06-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        ("clinical", "0021_auditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageEligibilityRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="FHIR priority: desired processing priority.",
                        max_length=255,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="FHIR purpose: auth-requirements, benefits, discovery, validation.",
                        max_length=255,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: request creation date.",
                        null=True,
                    ),
                ),
                (
                    "serviced_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR serviced[x]: service date or period start.",
                        null=True,
                    ),
                ),
                (
                    "serviced_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR servicedPeriod.end: service period end.",
                        null=True,
                    ),
                ),
                (
                    "insurance_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR insurance: coverages included in the request.",
                    ),
                ),
                (
                    "item_summary",
                    models.TextField(
                        blank=True, help_text="FHIR item: eligibility request items."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this eligibility request.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR insurer: target insurer for eligibility request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverage_eligibility_requests_as_insurer",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR patient: patient whose coverage eligibility is being requested.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_eligibility_requests",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "provider_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR provider: organization making the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverage_eligibility_requests_as_provider",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: request creation date.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this enrollment request.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coverage",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR coverage: coverage to enroll.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_requests",
                        to="clinical.coverage",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR insurer: target insurer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_requests_as_insurer",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR candidate: person to be enrolled when patient-resolvable.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_requests",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR provider: organization submitting enrollment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_requests_as_provider",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="FHIR url: canonical URL for the measure."
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the measure.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly measure name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly measure title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for the measure.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language measure description.",
                    ),
                ),
                (
                    "scoring",
                    models.CharField(
                        blank=True,
                        help_text="FHIR scoring: proportion, ratio, continuous-variable, cohort, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "measure_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: process, outcome, structure, patient-reported-outcome, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "group_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR group: populations, stratifiers, and supplemental data.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this measure.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this test script.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the test script.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly test script name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly test script title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for publication.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: test script description.",
                    ),
                ),
                (
                    "fixture_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR fixture: fixtures used by this script.",
                    ),
                ),
                (
                    "test_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR setup/test/teardown: summarized test actions and assertions.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this test script.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="FHIR name: report name.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: completed, in-progress, waiting, stopped, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        help_text="FHIR result: pass, fail, or pending.",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="FHIR score: overall test score.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tester",
                    models.CharField(
                        blank=True,
                        help_text="FHIR tester: name of the tester.",
                        max_length=255,
                    ),
                ),
                (
                    "issued",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR issued: when report was generated.",
                        null=True,
                    ),
                ),
                (
                    "participant_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR participant: servers/clients involved in the test.",
                    ),
                ),
                (
                    "action_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR setup/test/teardown.action: action results.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this test report.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_script",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR testScript: test script this report executed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="clinical.testscript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="FHIR outcome: queued, complete, error, or partial.",
                        max_length=30,
                    ),
                ),
                (
                    "disposition",
                    models.TextField(
                        blank=True, help_text="FHIR disposition: disposition message."
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: reconciliation creation date.",
                        null=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR paymentDate: date of payment.",
                        null=True,
                    ),
                ),
                (
                    "payment_amount",
                    models.CharField(
                        blank=True,
                        help_text="FHIR paymentAmount: amount paid.",
                        max_length=255,
                    ),
                ),
                (
                    "detail_summary",
                    models.TextField(
                        blank=True, help_text="FHIR detail: payment allocation details."
                    ),
                ),
                (
                    "process_note_summary",
                    models.TextField(
                        blank=True, help_text="FHIR processNote: processing notes."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this payment reconciliation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_issuer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR paymentIssuer: organization issuing payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_reconciliations",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR paymentStatus: status of the payment.",
                        max_length=255,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: notice creation date.",
                        null=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR paymentDate: expected or actual payment date.",
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        help_text="FHIR amount: payment amount.",
                        max_length=255,
                    ),
                ),
                (
                    "request_summary",
                    models.CharField(
                        blank=True,
                        help_text="FHIR request: request reference this notice relates to.",
                        max_length=255,
                    ),
                ),
                (
                    "response_summary",
                    models.CharField(
                        blank=True,
                        help_text="FHIR response: response reference this notice relates to.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this payment notice.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Local patient association when payment references patient data.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_notices",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR recipient: party notified about payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_notices",
                        to="clinical.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasureReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: complete, pending, or error.",
                        max_length=30,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: individual, subject-list, summary, or data-collection.",
                        max_length=30,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: when the report was generated.",
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.start: reporting period start.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="FHIR period.end: reporting period end.",
                        null=True,
                    ),
                ),
                (
                    "improvement_notation",
                    models.CharField(
                        blank=True,
                        help_text="FHIR improvementNotation: how improvement is calculated.",
                        max_length=255,
                    ),
                ),
                (
                    "group_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR group: measure score, populations, and stratifiers.",
                    ),
                ),
                (
                    "evaluated_resource_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR evaluatedResource: resources included in evaluation.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this measure report.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "measure",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR measure: measure this report is for when locally resolvable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="clinical.measure",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR subject: patient associated with the measure report when present.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_reports",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="FHIR outcome: queued, complete, error, or partial.",
                        max_length=30,
                    ),
                ),
                (
                    "disposition",
                    models.TextField(
                        blank=True, help_text="FHIR disposition: disposition message."
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: response creation date.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this enrollment response.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR organization: organization responding.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_responses",
                        to="clinical.organization",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR request: enrollment request being answered.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="clinical.enrollmentrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageEligibilityResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: active, cancelled, draft, or entered-in-error.",
                        max_length=30,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="FHIR purpose: auth-requirements, benefits, discovery, validation.",
                        max_length=255,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="FHIR outcome: queued, complete, error, or partial.",
                        max_length=30,
                    ),
                ),
                (
                    "disposition",
                    models.TextField(
                        blank=True, help_text="FHIR disposition: disposition message."
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True,
                        help_text="FHIR created: response creation date.",
                        null=True,
                    ),
                ),
                (
                    "insurance_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR insurance: benefits and eligibility details.",
                    ),
                ),
                (
                    "error_summary",
                    models.TextField(
                        blank=True, help_text="FHIR error: processing errors."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this eligibility response.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR insurer: party responsible for response.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverage_eligibility_responses",
                        to="clinical.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR patient: patient whose coverage eligibility was evaluated.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_eligibility_responses",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        help_text="FHIR request: eligibility request being answered.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="clinical.coverageeligibilityrequest",
                    ),
                ),
            ],
        ),
    ]
