# Generated by Django 4.2.4 on 2026-06-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clinical",
            "0022_coverageeligibilityrequest_enrollmentrequest_measure_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this code system.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the code system.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly code system name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly code system title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this code system.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language description of the code system.",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True,
                        help_text="FHIR content: not-present, example, fragment, complete, or supplement.",
                        max_length=30,
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        blank=True,
                        help_text="FHIR caseSensitive: whether code comparison is case sensitive.",
                        null=True,
                    ),
                ),
                (
                    "hierarchy_meaning",
                    models.CharField(
                        blank=True,
                        help_text="FHIR hierarchyMeaning: meaning of parent/child concept relationships.",
                        max_length=50,
                    ),
                ),
                (
                    "concept_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR concept: summarized code system concepts.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this code system.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this concept map.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the concept map.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly concept map name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly concept map title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this concept map.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language description of the concept map.",
                    ),
                ),
                (
                    "source_uri",
                    models.CharField(
                        blank=True,
                        help_text="FHIR source[x]: source value set or structure map context.",
                        max_length=500,
                    ),
                ),
                (
                    "target_uri",
                    models.CharField(
                        blank=True,
                        help_text="FHIR target[x]: target value set or structure map context.",
                        max_length=500,
                    ),
                ),
                (
                    "group_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR group: concept mappings and equivalence details.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this concept map.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this library.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the library.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly library name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly library title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this library.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language description of the library.",
                    ),
                ),
                (
                    "library_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: logic-library, model-definition, asset-collection, module-definition, or related type.",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="FHIR subject[x]: intended subject for the library.",
                        max_length=255,
                    ),
                ),
                (
                    "related_artifact_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR relatedArtifact: citations, dependencies, composed-of, and derived-from links.",
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR content: attachments containing library logic or related files.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this library.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this plan definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the plan definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly plan definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly plan definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this plan definition.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language description of the plan definition.",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: order-set, clinical-protocol, eca-rule, workflow-definition, or other plan type.",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="FHIR subject[x]: intended subject for the plan definition.",
                        max_length=255,
                    ),
                ),
                (
                    "goal_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR goal: goals this plan definition supports.",
                    ),
                ),
                (
                    "action_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR action: actions, triggers, conditions, inputs, and outputs.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this plan definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ValueSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this value set.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the value set.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly value set name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly value set title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this value set.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language description of the value set.",
                    ),
                ),
                (
                    "immutable",
                    models.BooleanField(
                        blank=True,
                        help_text="FHIR immutable: whether the value set definition may not change.",
                        null=True,
                    ),
                ),
                (
                    "compose_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR compose: include/exclude rules used to define the value set.",
                    ),
                ),
                (
                    "expansion_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR expansion: expanded codes when included in the resource.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this value set.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
