# Generated by Django 4.2.4 on 2026-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0023_codesystem_conceptmap_library_plandefinition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this activity definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the activity definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly activity definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly activity definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: activity definition description.",
                    ),
                ),
                (
                    "activity_kind",
                    models.CharField(
                        blank=True,
                        help_text="FHIR kind: resource type this activity creates.",
                        max_length=50,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="FHIR intent: proposal, plan, directive, order, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="FHIR priority: routine, urgent, asap, or stat.",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="FHIR code: detail of the activity to perform.",
                        max_length=255,
                    ),
                ),
                (
                    "participant_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR participant: participants expected to perform the activity.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this activity definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CapabilityStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this capability statement.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the capability statement.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly capability statement name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly capability statement title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language description of the capability statement.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="FHIR kind: instance, capability, or requirements.",
                        max_length=30,
                    ),
                ),
                (
                    "fhir_version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR fhirVersion: FHIR version supported.",
                        max_length=30,
                    ),
                ),
                (
                    "format_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR format/patchFormat: supported data formats.",
                    ),
                ),
                (
                    "rest_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR rest: RESTful capabilities and interactions.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this capability statement.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompartmentDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this compartment definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the compartment definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly compartment definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR name/title: human-friendly compartment label.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: compartment definition description.",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="FHIR code: Patient, Encounter, RelatedPerson, Practitioner, or Device.",
                        max_length=50,
                    ),
                ),
                (
                    "search",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR search: whether compartment can be used for search.",
                    ),
                ),
                (
                    "resource_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR resource: resources and search parameters included in this compartment.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this compartment definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this event definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the event definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly event definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly event definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: event definition description.",
                    ),
                ),
                (
                    "trigger_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR trigger: triggering events for this definition.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this event definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this example scenario.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the example scenario.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly example scenario name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly example scenario title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: example scenario description.",
                    ),
                ),
                (
                    "actor_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR actor: participants in the scenario.",
                    ),
                ),
                (
                    "instance_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR instance: resources used in the scenario.",
                    ),
                ),
                (
                    "process_summary",
                    models.TextField(
                        blank=True, help_text="FHIR process: scenario process steps."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this example scenario.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraphDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this graph definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the graph definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly graph definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly graph definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: graph traversal description.",
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        help_text="FHIR start: resource type where the graph starts.",
                        max_length=255,
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True,
                        help_text="FHIR profile: profile that describes graph instances.",
                        max_length=500,
                    ),
                ),
                (
                    "link_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR link: graph traversal links and target resources.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this graph definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImplementationGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this implementation guide.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the implementation guide.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly implementation guide name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly implementation guide title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language implementation guide description.",
                    ),
                ),
                (
                    "package_id",
                    models.CharField(
                        blank=True,
                        help_text="FHIR packageId: NPM package id for this guide.",
                        max_length=255,
                    ),
                ),
                (
                    "fhir_version_summary",
                    models.CharField(
                        blank=True,
                        help_text="FHIR fhirVersion: FHIR versions this guide targets.",
                        max_length=255,
                    ),
                ),
                (
                    "definition_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR definition: grouped resources, pages, parameters, and templates.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this implementation guide.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this message definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the message definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly message definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly message definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: message definition behavior and use.",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        help_text="FHIR event[x]: event code or canonical event definition.",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="FHIR category: consequence, currency, or notification.",
                        max_length=30,
                    ),
                ),
                (
                    "response_required",
                    models.CharField(
                        blank=True,
                        help_text="FHIR responseRequired: always, on-error, never, or on-success.",
                        max_length=30,
                    ),
                ),
                (
                    "focus_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR focus: resources that must be present in messages.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this message definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NamingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="FHIR name: computer-friendly naming system name.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="FHIR kind: codesystem, identifier, or root.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: naming system description.",
                    ),
                ),
                (
                    "unique_id_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR uniqueId: unique identifiers such as URI, OID, UUID, or other ids.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this naming system.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperationDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this operation definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the operation definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly operation definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly operation definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: operation or named query behavior.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="FHIR kind: operation or query.",
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="FHIR code: name used to invoke the operation.",
                        max_length=255,
                    ),
                ),
                (
                    "resource_summary",
                    models.CharField(
                        blank=True,
                        help_text="FHIR resource: resource types this operation applies to.",
                        max_length=500,
                    ),
                ),
                (
                    "system",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR system: whether operation can be invoked at system level.",
                    ),
                ),
                (
                    "type_level",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR type: whether operation can be invoked at resource type level.",
                    ),
                ),
                (
                    "instance",
                    models.BooleanField(
                        default=False,
                        help_text="FHIR instance: whether operation can be invoked at instance level.",
                    ),
                ),
                (
                    "parameter_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR parameter: operation input/output parameters.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this operation definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this search parameter.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the search parameter.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly search parameter name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title/name: human-friendly search parameter label.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: search parameter purpose and behavior.",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="FHIR code: code used in search URLs.",
                        max_length=255,
                    ),
                ),
                (
                    "base_summary",
                    models.CharField(
                        blank=True,
                        help_text="FHIR base: resource types this search parameter applies to.",
                        max_length=500,
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: number, date, string, token, reference, composite, quantity, uri, or special.",
                        max_length=50,
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        blank=True,
                        help_text="FHIR expression: FHIRPath expression over the resource.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this search parameter.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpecimenDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this specimen definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the specimen definition.",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR typeCollected/title: human-friendly specimen definition label.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: specimen definition description.",
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        blank=True,
                        help_text="FHIR typeCollected: kind of specimen to collect.",
                        max_length=255,
                    ),
                ),
                (
                    "collection_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR collection: preferred collection method and requirements.",
                    ),
                ),
                (
                    "type_tested_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR typeTested: specimen testing details and handling requirements.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this specimen definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StructureDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this structure definition.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the structure definition.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly structure definition name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly structure definition title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: natural language profile/extension description.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="FHIR kind: primitive-type, complex-type, resource, or logical.",
                        max_length=50,
                    ),
                ),
                (
                    "abstract",
                    models.BooleanField(
                        blank=True,
                        help_text="FHIR abstract: whether this structure is abstract.",
                        null=True,
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        blank=True,
                        help_text="FHIR type: constrained FHIR type/resource.",
                        max_length=255,
                    ),
                ),
                (
                    "base_definition",
                    models.CharField(
                        blank=True,
                        help_text="FHIR baseDefinition: base structure this definition constrains.",
                        max_length=500,
                    ),
                ),
                (
                    "derivation",
                    models.CharField(
                        blank=True,
                        help_text="FHIR derivation: specialization or constraint.",
                        max_length=30,
                    ),
                ),
                (
                    "element_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR snapshot/differential: summarized element definitions.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this structure definition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StructureMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this structure map.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the structure map.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly structure map name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title: human-friendly structure map title.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: structure mapping description.",
                    ),
                ),
                (
                    "structure_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR structure: source/target structures used by this map.",
                    ),
                ),
                (
                    "group_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR group: transformation groups and rules.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this structure map.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TerminologyCapabilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="FHIR url: canonical URL for this terminology capabilities resource.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="FHIR version: business version of the terminology capabilities resource.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="FHIR name: computer-friendly terminology capabilities name.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="FHIR title/name: human-friendly terminology capabilities label.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="FHIR status: draft, active, retired, or unknown.",
                        max_length=30,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="FHIR publisher: organization or individual responsible for this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="FHIR date: publication/change date.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="FHIR description: terminology server capabilities description.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="FHIR kind: instance, capability, or requirements.",
                        max_length=30,
                    ),
                ),
                (
                    "code_system_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR codeSystem: supported code systems and versions.",
                    ),
                ),
                (
                    "expansion_summary",
                    models.TextField(
                        blank=True,
                        help_text="FHIR expansion: expansion behavior and parameters.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Imported notes or source text for this terminology capabilities resource.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
