# Generated by Django 4.2.4 on 2026-08-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientprofile_options"),
        ("clinical", "0025_basic_biologicallyderivedproduct_catalogentry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bowel", "Bowel movement"),
                            ("diet", "Dietary"),
                            ("symptom", "Symptom"),
                            ("activity", "Activity"),
                            ("medication", "Medication"),
                            ("sleep", "Sleep"),
                            ("mood", "Mood"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Kind of event being logged.",
                        max_length=30,
                    ),
                ),
                (
                    "logged_at",
                    models.DateTimeField(help_text="When the event happened."),
                ),
                (
                    "summary",
                    models.CharField(help_text="Short description.", max_length=255),
                ),
                (
                    "details",
                    models.TextField(blank=True, help_text="Optional extra notes."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this quick log belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_logs",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick Log",
                "verbose_name_plural": "Quick Logs",
                "ordering": ("-logged_at", "-created_at", "-id"),
            },
        ),
    ]
