# Generated by Django 4.2.4 on 2026-03-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='clinical_documents/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patientprofile')),
            ],
        ),
    ]
