# Generated by Django 4.2.4 on 2026-06-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "clinical",
            "0007_device_practitionerrole_servicerequest_episodeofcare_and_more",
        ),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicaldocument",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_documents",
                to="clinical.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custodied_documents",
                to="clinical.organization",
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="clinical.encounter",
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="related_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to_documents",
                to="documents.clinicaldocument",
            ),
        ),
    ]
