"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from config.credential_storage import CredentialStorageError, get_configured_secret
from config.database import build_default_database_config, env_flag
from config.env import load_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_env(
    BASE_DIR,
    env_file_name=os.getenv("DJANGO_ENV_FILE", ".env"),
    example_file_name=os.getenv("DJANGO_ENV_EXAMPLE_FILE", ".env.example"),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = (
        get_configured_secret("SECRET_KEY")
        or "django-insecure-development-only-change-me"
    )
except CredentialStorageError as error:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(str(error)) from error

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DEBUG", default=True)

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "config.apps.HolyFHIRAuthConfig",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "patients",
    "clinical",
    "documents",
    "fhir",
    "system_settings",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "system_settings.middleware.AppLockMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "patients.context_processors.admin_recent_patients",
                "system_settings.context_processors.system_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = build_default_database_config(BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "America/New_York")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Desktop/local-first behavior: keep the owner signed in for a long time.
# The session can still be cleared by deleting app data, clearing cookies, or changing secrets.
ONE_HUNDRED_YEARS_IN_SECONDS = 60 * 60 * 24 * 365 * 100
SESSION_COOKIE_AGE = ONE_HUNDRED_YEARS_IN_SECONDS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Login brute-force protection. This is local cache-backed throttling for the
# desktop app, not account recovery or remote abuse prevention.
HOLYFHIR_LOGIN_MAX_ATTEMPTS_PER_USERNAME = 5
HOLYFHIR_LOGIN_MAX_ATTEMPTS_PER_CLIENT = 20
HOLYFHIR_LOGIN_LOCKOUT_SECONDS = 15 * 60

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "HolyFHIR Personal EMR",
    "site_header": "HolyFHIR Personal EMR",
    "site_brand": "HolyFHIR Personal EMR",
    "site_logo": None,  # e.g. "my_app/static/images/logo.png"
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_custom.js",
    # "show_ui_builder": True,
    "changeform_format": "single",
    "search_model": "patients.PatientProfile",
    "order_with_respect_to": [
        "patients",
        "clinical",
        "documents",
        "fhir",
        "System",
    ],
    "icons": {
        "auth": "fas fa-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "system": "fas fa-cog",
        "system_settings.SystemSettings": "fas fa-sliders-h",
        "patients": "fas fa-hospital-user",
        "patients.PatientProfile": "fas fa-id-card",
        "clinical": "fas fa-notes-medical",
        "clinical.ActivityDefinition": "fas fa-play-circle",
        "clinical.CapabilityStatement": "fas fa-server",
        "clinical.CompartmentDefinition": "fas fa-boxes",
        "clinical.EventDefinition": "fas fa-bolt",
        "clinical.ExampleScenario": "fas fa-theater-masks",
        "clinical.GraphDefinition": "fas fa-project-diagram",
        "clinical.ImplementationGuide": "fas fa-book-open",
        "clinical.MessageDefinition": "fas fa-envelope-open-text",
        "clinical.NamingSystem": "fas fa-fingerprint",
        "clinical.OperationDefinition": "fas fa-terminal",
        "clinical.SearchParameter": "fas fa-search",
        "clinical.SpecimenDefinition": "fas fa-vials",
        "clinical.StructureDefinition": "fas fa-layer-group",
        "clinical.StructureMap": "fas fa-random",
        "clinical.TerminologyCapabilities": "fas fa-language",
        "clinical.Account": "fas fa-wallet",
        "clinical.Appointment": "fas fa-calendar-check",
        "clinical.AppointmentResponse": "fas fa-calendar-alt",
        "clinical.AuditEvent": "fas fa-user-shield",
        "clinical.ChargeItem": "fas fa-tags",
        "clinical.Claim": "fas fa-file-invoice",
        "clinical.ClaimResponse": "fas fa-receipt",
        "clinical.BinaryResource": "fas fa-file-code",
        "clinical.BodyStructure": "fas fa-diagnoses",
        "clinical.Composition": "fas fa-file-alt",
        "clinical.Condition": "fas fa-heartbeat",
        "clinical.AdverseEvent": "fas fa-exclamation-circle",
        "clinical.Allergy": "fas fa-exclamation-triangle",
        "clinical.ClinicalImpression": "fas fa-notes-medical",
        "clinical.DetectedIssue": "fas fa-shield-alt",
        "clinical.DeviceDefinition": "fas fa-microchip",
        "clinical.DeviceMetric": "fas fa-tachometer-alt",
        "clinical.DeviceRequest": "fas fa-toolbox",
        "clinical.DeviceUseStatement": "fas fa-notes-medical",
        "clinical.DiagnosticReport": "fas fa-file-medical-alt",
        "clinical.DocumentManifest": "fas fa-folder-open",
        "clinical.Invoice": "fas fa-file-invoice-dollar",
        "clinical.Endpoint": "fas fa-plug",
        "clinical.FamilyMemberHistory": "fas fa-people-arrows",
        "clinical.FHIRList": "fas fa-list",
        "clinical.Flag": "fas fa-flag",
        "clinical.GuidanceResponse": "fas fa-route",
        "clinical.HealthcareService": "fas fa-clinic-medical",
        "clinical.ImagingStudy": "fas fa-x-ray",
        "clinical.Medication": "fas fa-pills",
        "clinical.MedicationAdministration": "fas fa-prescription-bottle",
        "clinical.MedicationCatalog": "fas fa-capsules",
        "clinical.MedicationDispense": "fas fa-prescription-bottle-alt",
        "clinical.MedicationKnowledge": "fas fa-book-medical",
        "clinical.Immunization": "fas fa-syringe",
        "clinical.ImmunizationEvaluation": "fas fa-check-circle",
        "clinical.ImmunizationRecommendation": "fas fa-calendar-check",
        "clinical.InsurancePlan": "fas fa-umbrella",
        "clinical.Media": "fas fa-photo-video",
        "clinical.MolecularSequence": "fas fa-dna",
        "clinical.NutritionOrder": "fas fa-utensils",
        "clinical.Observation": "fas fa-chart-line",
        "clinical.ObservationDefinition": "fas fa-ruler-combined",
        "clinical.OrganizationAffiliation": "fas fa-handshake",
        "clinical.Communication": "fas fa-comments",
        "clinical.CommunicationRequest": "fas fa-paper-plane",
        "clinical.Consent": "fas fa-file-signature",
        "clinical.Coverage": "fas fa-id-card-alt",
        "clinical.Encounter": "fas fa-stethoscope",
        "clinical.ExplanationOfBenefit": "fas fa-file-invoice-dollar",
        "clinical.CareTeam": "fas fa-user-friends",
        "clinical.CarePlan": "fas fa-clipboard-list",
        "clinical.Procedure": "fas fa-procedures",
        "clinical.Specimen": "fas fa-vial",
        "clinical.ServiceRequest": "fas fa-tasks",
        "clinical.EpisodeOfCare": "fas fa-project-diagram",
        "clinical.Device": "fas fa-laptop-medical",
        "clinical.FHIRGroup": "fas fa-layer-group",
        "clinical.Goal": "fas fa-bullseye",
        "clinical.Person": "fas fa-user-circle",
        "clinical.Provenance": "fas fa-history",
        "clinical.Questionnaire": "fas fa-clipboard-question",
        "clinical.QuestionnaireResponse": "fas fa-clipboard-list",
        "clinical.RequestGroup": "fas fa-stream",
        "clinical.PractitionerRole": "fas fa-id-badge",
        "clinical.Practitioner": "fas fa-user-md",
        "clinical.RelatedPerson": "fas fa-address-book",
        "clinical.RiskAssessment": "fas fa-chart-pie",
        "clinical.Schedule": "fas fa-calendar",
        "clinical.Slot": "fas fa-clock",
        "clinical.Substance": "fas fa-flask",
        "clinical.SupplyDelivery": "fas fa-truck",
        "clinical.SupplyRequest": "fas fa-box-open",
        "clinical.Task": "fas fa-tasks",
        "clinical.VisionPrescription": "fas fa-glasses",
        "clinical.Organization": "fas fa-hospital",
        "clinical.Location": "fas fa-map-marker-alt",
        "documents": "fas fa-file-medical",
        "documents.ClinicalDocument": "fas fa-file-pdf",
        "fhir": "fas fa-exchange-alt",
        "fhir.FHIRLink": "fas fa-link",
        "fhir.FHIRResourceSnapshot": "fas fa-database",
        "interop": "fas fa-exchange-alt",
    },
    "custom_links": {
        "System": [
            {
                "name": "Settings",
                "url": "admin_settings",
                "icon": "fas fa-cog",
                "permissions": ["auth.view_user"],
            }
        ],
        "patients": [
            {
                "name": "Add Patient",
                "url": "admin:patients_patientprofile_add",
                "icon": "fas fa-user-plus",
                "permissions": ["patients.add_patientprofile"],
            }
        ],
        "clinical": [
            {
                "name": "Clinical Resources",
                "url": "new_clinical_resources_directory",
                "icon": "fas fa-notes-medical",
                "permissions": ["clinical.view_condition"],
            },
            {
                "name": "Care Team Info",
                "url": "clinical_care_team_directory",
                "icon": "fas fa-user-friends",
                "permissions": ["clinical.view_careteam"],
            },
            {
                "name": "Health Trends",
                "url": "observation_charts",
                "icon": "fas fa-chart-area",
                "permissions": ["clinical.view_observation"],
            },
        ],
        "fhir": [
            {
                "name": "FHIR / Interop",
                "url": "fhir_interop_hub",
                "icon": "fas fa-exchange-alt",
                "permissions": ["fhir.view_fhirresourcesnapshot"],
            },
            {
                "name": "Import Data",
                "url": "fhir_import",
                "icon": "fas fa-file-import",
                "permissions": ["fhir.add_fhirresourcesnapshot"],
            },
            {
                "name": "Export Data",
                "url": "fhir_export",
                "icon": "fas fa-file-export",
                "permissions": ["fhir.view_fhirresourcesnapshot"],
            },
            {
                "name": "FHIR Explorer",
                "url": "fhir_explorer",
                "icon": "fas fa-search",
                "permissions": ["fhir.view_fhirresourcesnapshot"],
            },
        ],
    },
    "hide_apps": [
        "auth",
    ],
    "hide_models": [
        "patients.RecoveryCredential",
        "clinical.Account",
        "clinical.ActivityDefinition",
        "clinical.AdverseEvent",
        "clinical.Allergy",
        "clinical.Appointment",
        "clinical.AppointmentResponse",
        "clinical.AuditEvent",
        "clinical.Basic",
        "clinical.BinaryResource",
        "clinical.BiologicallyDerivedProduct",
        "clinical.BodyStructure",
        "clinical.CapabilityStatement",
        "clinical.CarePlan",
        "clinical.CareTeam",
        "clinical.CareTeamParticipant",
        "clinical.CatalogEntry",
        "clinical.ChargeItem",
        "clinical.ChargeItemDefinition",
        "clinical.Claim",
        "clinical.ClaimResponse",
        "clinical.ClinicalImpression",
        "clinical.ClinicalImpressionFinding",
        "clinical.CodeSystem",
        "clinical.Communication",
        "clinical.CommunicationRequest",
        "clinical.CompartmentDefinition",
        "clinical.Composition",
        "clinical.ConceptMap",
        "clinical.Condition",
        "clinical.Consent",
        "clinical.Contract",
        "clinical.Coverage",
        "clinical.CoverageEligibilityRequest",
        "clinical.CoverageEligibilityResponse",
        "clinical.DetectedIssue",
        "clinical.Device",
        "clinical.DeviceDefinition",
        "clinical.DeviceMetric",
        "clinical.DeviceRequest",
        "clinical.DeviceUseStatement",
        "clinical.DiagnosticReport",
        "clinical.DocumentManifest",
        "clinical.EffectEvidenceSynthesis",
        "clinical.Encounter",
        "clinical.Endpoint",
        "clinical.EnrollmentRequest",
        "clinical.EnrollmentResponse",
        "clinical.EpisodeOfCare",
        "clinical.EventDefinition",
        "clinical.Evidence",
        "clinical.EvidenceVariable",
        "clinical.ExampleScenario",
        "clinical.ExplanationOfBenefit",
        "clinical.FamilyMemberHistory",
        "clinical.FamilyMemberHistoryCondition",
        "clinical.FHIRCompactResource",
        "clinical.FHIRGroup",
        "clinical.FHIRGroupMember",
        "clinical.FHIRList",
        "clinical.Flag",
        "clinical.Goal",
        "clinical.GraphDefinition",
        "clinical.GuidanceResponse",
        "clinical.HealthcareService",
        "clinical.ImagingStudy",
        "clinical.Immunization",
        "clinical.ImmunizationEvaluation",
        "clinical.ImmunizationRecommendation",
        "clinical.ImplementationGuide",
        "clinical.InsurancePlan",
        "clinical.Invoice",
        "clinical.Library",
        "clinical.Linkage",
        "clinical.Location",
        "clinical.Measure",
        "clinical.MeasureReport",
        "clinical.Media",
        "clinical.Medication",
        "clinical.MedicationAdministration",
        "clinical.MedicationCatalog",
        "clinical.MedicationDispense",
        "clinical.MedicationKnowledge",
        "clinical.MedicinalProduct",
        "clinical.MedicinalProductAuthorization",
        "clinical.MedicinalProductContraindication",
        "clinical.MedicinalProductIndication",
        "clinical.MedicinalProductIngredient",
        "clinical.MedicinalProductInteraction",
        "clinical.MedicinalProductManufactured",
        "clinical.MedicinalProductPackaged",
        "clinical.MedicinalProductPharmaceutical",
        "clinical.MedicinalProductUndesirableEffect",
        "clinical.MessageDefinition",
        "clinical.MessageHeader",
        "clinical.MolecularSequence",
        "clinical.NamingSystem",
        "clinical.NutritionOrder",
        "clinical.Observation",
        "clinical.ObservationDefinition",
        "clinical.OperationDefinition",
        "clinical.OperationOutcome",
        "clinical.Organization",
        "clinical.OrganizationAffiliation",
        "clinical.Parameters",
        "clinical.PaymentNotice",
        "clinical.PaymentReconciliation",
        "clinical.Person",
        "clinical.PersonLink",
        "clinical.PlanDefinition",
        "clinical.Practitioner",
        "clinical.PractitionerRole",
        "clinical.Procedure",
        "clinical.ProcedurePerformer",
        "clinical.Provenance",
        "clinical.Questionnaire",
        "clinical.QuestionnaireResponse",
        "clinical.RelatedPerson",
        "clinical.RequestGroup",
        "clinical.ResearchDefinition",
        "clinical.ResearchElementDefinition",
        "clinical.ResearchStudy",
        "clinical.ResearchSubject",
        "clinical.RiskAssessment",
        "clinical.RiskEvidenceSynthesis",
        "clinical.Schedule",
        "clinical.SearchParameter",
        "clinical.ServiceRequest",
        "clinical.Slot",
        "clinical.Specimen",
        "clinical.SpecimenDefinition",
        "clinical.StructureDefinition",
        "clinical.StructureMap",
        "clinical.Subscription",
        "clinical.Substance",
        "clinical.SubstanceNucleicAcid",
        "clinical.SubstancePolymer",
        "clinical.SubstanceProtein",
        "clinical.SubstanceReferenceInformation",
        "clinical.SubstanceSourceMaterial",
        "clinical.SubstanceSpecification",
        "clinical.SupplyDelivery",
        "clinical.SupplyRequest",
        "clinical.Task",
        "clinical.TerminologyCapabilities",
        "clinical.TestReport",
        "clinical.TestScript",
        "clinical.ValueSet",
        "clinical.VerificationResult",
        "clinical.VisionPrescription",
        "system_settings.SystemSettings",
        "fhir.FHIRLink",
        "fhir.FHIRResourceSnapshot",
    ],
    # "hide_models": [
    #     "auth.Group",
    #     "fhir.FHIRLink",
    # ],
}


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
