"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from config.database import build_default_database_config, env_flag
from config.env import load_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_env(
    BASE_DIR,
    env_file_name=os.getenv("DJANGO_ENV_FILE", ".env"),
    example_file_name=os.getenv("DJANGO_ENV_EXAMPLE_FILE", ".env.example"),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag('DEBUG', default=True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'config.apps.HolyFHIRAuthConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patients',
    'clinical',
    'documents',
    'fhir',
    'system_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'system_settings.middleware.AppLockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "patients.context_processors.admin_recent_patients",
                "system_settings.context_processors.system_settings",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = build_default_database_config(BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIME_ZONE", "America/New_York")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Desktop/local-first behavior: keep the owner signed in for a long time.
# The session can still be cleared by deleting app data, clearing cookies, or changing secrets.
ONE_HUNDRED_YEARS_IN_SECONDS = 60 * 60 * 24 * 365 * 100
SESSION_COOKIE_AGE = ONE_HUNDRED_YEARS_IN_SECONDS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Login brute-force protection. This is local cache-backed throttling for the
# desktop app, not account recovery or remote abuse prevention.
HOLYFHIR_LOGIN_MAX_ATTEMPTS_PER_USERNAME = 5
HOLYFHIR_LOGIN_MAX_ATTEMPTS_PER_CLIENT = 20
HOLYFHIR_LOGIN_LOCKOUT_SECONDS = 15 * 60

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "HolyFHIR Personal EMR",
    "site_header": "HolyFHIR Personal EMR",
    "site_brand": "HolyFHIR Personal EMR",
    "site_logo": None,  # e.g. "my_app/static/images/logo.png"
    # "show_ui_builder": True,
    "changeform_format": "single",

    "search_model": "patients.PatientProfile",
    "order_with_respect_to": [
        "patients",
        "clinical",
        "documents",
        "fhir",
        "System",
    ],


    "icons": {
        "auth": "fas fa-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "system": "fas fa-cog",
        "system_settings.SystemSettings": "fas fa-sliders-h",

        "patients": "fas fa-hospital-user",
        "patients.PatientProfile": "fas fa-id-card",

        "clinical": "fas fa-notes-medical",
        "clinical.Condition": "fas fa-heartbeat",
        "clinical.Allergy": "fas fa-exclamation-triangle",
        "clinical.Medication": "fas fa-pills",
        "clinical.Immunization": "fas fa-syringe",
        "clinical.Observation": "fas fa-chart-line",
        "clinical.Encounter": "fas fa-stethoscope",

        "documents": "fas fa-file-medical",
        "documents.ClinicalDocument": "fas fa-file-pdf",

        "fhir": "fas fa-exchange-alt",
        "fhir.FHIRLink": "fas fa-link",
        "fhir.FHIRResourceSnapshot": "fas fa-database",
        "interop": "fas fa-exchange-alt",
    },
    "custom_links": {
        "System": [{
            "name": "Settings",
            "url": "admin_settings",
            "icon": "fas fa-cog",
            "permissions": ["auth.view_user"],
        }],
        "patients": [{
            "name": "Add Patient",
            "url": "admin:patients_patientprofile_add",
            "icon": "fas fa-user-plus",
            "permissions": ["patients.add_patientprofile"],
        }],
        "clinical": [{
            "name": "Observation Charts",
            "url": "observation_charts",
            "icon": "fas fa-chart-area",
            "permissions": ["clinical.view_observation"],
        }],
        "fhir": [{
            "name": "FHIR / Interop",
            "url": "fhir_interop_hub",
            "icon": "fas fa-exchange-alt",
            "permissions": ["fhir.view_fhirresourcesnapshot"],
        }, {
            "name": "Import FHIR Data",
            "url": "fhir_import",
            "icon": "fas fa-file-import",
            "permissions": ["fhir.add_fhirresourcesnapshot"],
        }],
    },
    
    "hide_apps": [
        "auth",
    ],

    "hide_models": [
        "patients.RecoveryCredential",
        "system_settings.SystemSettings",
        "fhir.FHIRLink",
        "fhir.FHIRResourceSnapshot",
    ],

# "hide_models": [
#     "auth.Group",
#     "fhir.FHIRLink",
# ],

}


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
