# Generated by Django 4.2.4 on 2026-06-18

from django.db import migrations, models


def classify_existing_snapshots(apps, schema_editor):
    FHIRResourceSnapshot = apps.get_model("fhir", "FHIRResourceSnapshot")

    FHIRResourceSnapshot.objects.filter(
        validation_errors=["Unsupported resource type."],
    ).update(
        import_status="snapshot_only",
        is_valid=True,
        validation_errors=[],
    )

    FHIRResourceSnapshot.objects.filter(
        is_valid=False,
    ).exclude(
        import_status="snapshot_only",
    ).update(import_status="invalid")


class Migration(migrations.Migration):
    dependencies = [
        ("fhir", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fhirresourcesnapshot",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("imported", "Imported"),
                    ("snapshot_only", "Snapshot only"),
                    ("invalid", "Invalid"),
                ],
                default="imported",
                max_length=30,
            ),
        ),
        migrations.RunPython(classify_existing_snapshots, migrations.RunPython.noop),
    ]
