# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLockout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(choices=[("username", "Username"), ("client", "Client")], max_length=20),
                ),
                ("key", models.CharField(max_length=64)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Login Lockout",
                "verbose_name_plural": "Login Lockouts",
            },
        ),
        migrations.AddConstraint(
            model_name="loginlockout",
            constraint=models.UniqueConstraint(
                fields=("scope", "key"),
                name="unique_login_lockout_scope_key",
            ),
        ),
    ]
