# Generated by Django 4.2.4 on 2026-04-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_recoverycredential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
    ]
