# Generated by Codex on 2026-04-15

import system_settings.models
from django.conf import settings
from django.db import migrations, models


def set_existing_time_zone(apps, schema_editor):
    SystemSettings = apps.get_model("system_settings", "SystemSettings")
    SystemSettings.objects.update(time_zone=getattr(settings, "TIME_ZONE", "America/New_York"))


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="time_zone",
            field=models.CharField(
                default=system_settings.models.default_time_zone,
                help_text="Used to display exact times, such as encounters, observations, imports, and lockouts.",
                max_length=64,
            ),
        ),
        migrations.RunPython(set_existing_time_zone, migrations.RunPython.noop),
    ]
