# Generated by Codex on 2026-07-07

from django.db import migrations, models

import system_settings.themes


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0003_systemsettings_locking_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="app_theme",
            field=models.CharField(
                choices=system_settings.themes.THEME_CHOICES,
                default=system_settings.themes.DEFAULT_THEME,
                help_text="Controls FamilyChartVault branding assets such as the logo and favicon.",
                max_length=32,
            ),
        ),
    ]
