# Generated by Codex on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0004_systemsettings_app_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="document_files_encrypted",
            field=models.BooleanField(
                "Protect uploaded documents",
                default=False,
                help_text="Store the user's choice for document file protection. Existing files are not converted automatically yet.",
            ),
        ),
    ]
